-- BLOOM APARTMENT v3 — chạy toàn bộ tệp trong Supabase SQL Editor.
create extension if not exists pgcrypto;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

create table if not exists public.properties(id uuid primary key default gen_random_uuid(),name text not null unique,address text,phone text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.properties add column if not exists short_name text;
alter table public.properties add column if not exists owner_name text;
alter table public.properties add column if not exists owner_phone text;
alter table public.properties add column if not exists email text;
alter table public.properties add column if not exists tax_code text;
alter table public.properties add column if not exists total_floors int not null default 4;
alter table public.properties add column if not exists notes text;
create table if not exists public.property_settings(id uuid primary key default gen_random_uuid(),property_id uuid not null unique references public.properties(id) on delete cascade,electric_rate numeric(12,2) not null default 4000,water_rate numeric(12,2) not null default 0,default_service_fee numeric(14,2) not null default 0,billing_close_day int not null default 28 check(billing_close_day between 1 and 28),payment_due_day int not null default 5 check(payment_due_day between 1 and 28),bank_name text,bank_account text,bank_account_name text,qr_template text default 'compact2',invoice_note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.rooms(id uuid primary key default gen_random_uuid(),property_id uuid not null references public.properties(id),room_number text not null,floor int,area numeric(8,2),base_rent numeric(14,2) not null default 0,status text not null default 'vacant' check(status in('vacant','occupied','maintenance','reserved')),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(property_id,room_number));
create table if not exists public.tenants(id uuid primary key default gen_random_uuid(),full_name text not null,phone text,email text,nationality text not null default 'Việt Nam',identity_type text default 'CCCD',identity_number text,date_of_birth date,permanent_address text,emergency_contact text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.leases(id uuid primary key default gen_random_uuid(),room_id uuid not null references public.rooms(id),representative_tenant_id uuid references public.tenants(id),start_date date not null,end_date date not null,monthly_rent numeric(14,2) not null default 0,deposit_amount numeric(14,2) not null default 0,payment_due_day int not null default 5 check(payment_due_day between 1 and 28),status text not null default 'active' check(status in('draft','active','expired','terminated')),ended_at date,end_reason text,deposit_refunded numeric(14,2) not null default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date>=start_date));
create table if not exists public.lease_tenants(lease_id uuid not null references public.leases(id) on delete cascade,tenant_id uuid not null references public.tenants(id),is_representative boolean not null default false,move_in_date date,move_out_date date,primary key(lease_id,tenant_id));
create table if not exists public.tenant_visas(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,visa_number text,visa_type text,issued_date date,expiry_date date not null,issuing_country text,document_url text,status text not null default 'active' check(status in('active','renewed','expired','cancelled')),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.billing_periods(id uuid primary key default gen_random_uuid(),property_id uuid not null references public.properties(id),period text not null check(period ~ '^\d{4}-(0[1-9]|1[0-2])$'),status text not null default 'open' check(status in('open','locked')),due_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(property_id,period));
create table if not exists public.monthly_room_records(id uuid primary key default gen_random_uuid(),billing_period_id uuid not null references public.billing_periods(id) on delete cascade,room_id uuid not null references public.rooms(id),lease_id uuid references public.leases(id),rent numeric(14,2) not null default 0,electric_start numeric(12,2) not null default 0,electric_end numeric(12,2) not null default 0,electric_rate numeric(12,2) not null default 4000,water_start numeric(12,2) not null default 0,water_end numeric(12,2) not null default 0,water_rate numeric(12,2) not null default 0,service_fee numeric(14,2) not null default 0,other_fee numeric(14,2) not null default 0,discount numeric(14,2) not null default 0,previous_debt numeric(14,2) not null default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(billing_period_id,room_id),check(electric_end>=electric_start),check(water_end>=water_start));
create table if not exists public.invoices(id uuid primary key default gen_random_uuid(),record_id uuid not null unique references public.monthly_room_records(id),invoice_number text unique,issued_at timestamptz not null default now(),due_date date,total_amount numeric(14,2) not null default 0,paid_amount numeric(14,2) not null default 0,status text not null default 'unpaid' check(status in('draft','unpaid','partial','paid','overdue','cancelled')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),invoice_id uuid not null references public.invoices(id),amount numeric(14,2) not null check(amount>0),paid_at timestamptz not null default now(),method text not null default 'transfer' check(method in('cash','transfer','other')),reference text,notes text,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id bigint generated always as identity primary key,action text not null,entity_type text not null,entity_id text,details jsonb,created_at timestamptz not null default now());

create index if not exists rooms_status_idx on public.rooms(status); create index if not exists leases_end_date_idx on public.leases(end_date); create index if not exists visas_expiry_idx on public.tenant_visas(expiry_date); create index if not exists records_period_idx on public.monthly_room_records(billing_period_id); create index if not exists payments_invoice_idx on public.payments(invoice_id);
do $$ declare t text; begin foreach t in array array['properties','property_settings','rooms','tenants','leases','tenant_visas','billing_periods','monthly_room_records','invoices'] loop execute format('drop trigger if exists set_%I_updated_at on public.%I',t,t); execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['properties','property_settings','rooms','tenants','leases','lease_tenants','tenant_visas','billing_periods','monthly_room_records','invoices','payments','audit_logs'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

insert into public.properties(name,address) values('Bloom Apartment','Đà Nẵng') on conflict(name) do nothing;
insert into public.property_settings(property_id) select id from public.properties where name='Bloom Apartment' on conflict(property_id) do nothing;
insert into public.rooms(property_id,room_number,floor,status) select p.id,v.room,left(v.room,1)::int,'vacant' from public.properties p cross join(values('101'),('102'),('103'),('104'),('105'),('201'),('202'),('203'),('204'),('205'),('301'),('302'),('303'),('304'),('305'),('401'),('402'),('403'),('404'),('405'))v(room) where p.name='Bloom Apartment' on conflict(property_id,room_number) do nothing;
