create table if not exists public.room_bills (
  id bigint generated by default as identity primary key,
  period text not null check (period ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  room text not null check (char_length(room) between 1 and 30),
  rent numeric not null default 0 check (rent >= 0),
  service numeric not null default 0 check (service >= 0),
  meter_start numeric not null default 0 check (meter_start >= 0),
  meter_end numeric not null default 0 check (meter_end >= meter_start),
  electric_rate numeric not null default 4000 check (electric_rate >= 0),
  previous_debt numeric not null default 0 check (previous_debt >= 0),
  paid boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (period, room)
);

create index if not exists room_bills_period_idx on public.room_bills(period);

alter table public.room_bills enable row level security;

insert into public.room_bills
  (period, room, rent, service, meter_start, meter_end, electric_rate, previous_debt)
values
  ('2026-09','101',0,0,635,867,3800,0),
  ('2026-09','102',0,0,1093,1744,4000,0),
  ('2026-09','103',4500000,200000,348,464,4000,0),
  ('2026-09','104',4200000,200000,418,576,4000,0),
  ('2026-09','105',0,0,435,472,4000,200000),
  ('2026-09','201',5000000,200000,410,502,4000,0),
  ('2026-09','202',5000000,200000,393,482,4000,0),
  ('2026-09','203',4300000,400000,328,508,4000,0),
  ('2026-09','204',4800000,200000,355,499,4000,800000),
  ('2026-09','205',5000000,200000,353,475,4000,0),
  ('2026-09','301',4600000,400000,358,494,4000,0),
  ('2026-09','302',5700000,400000,1296,1894,4000,0),
  ('2026-09','303',4500000,150000,257,393,4000,0),
  ('2026-09','304',5000000,150000,482,748,4000,0),
  ('2026-09','305',5000000,200000,708,1102,4000,0),
  ('2026-09','401',5500000,400000,1115,1584,4000,0),
  ('2026-09','402',6000000,400000,464,782,4000,0),
  ('2026-09','403',4700000,400000,328,506,4000,0),
  ('2026-09','404',5500000,300000,186,316,4000,0),
  ('2026-09','405',4500000,200000,456,646,4000,0)
on conflict (period, room) do nothing;

-- Không tạo policy công khai. Chỉ API phía Vercel dùng service role mới truy cập được bảng.
