const crypto = require('node:crypto');

function reply(res,status,data){res.status(status).setHeader('Cache-Control','no-store').json(data)}
function safeEqual(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function role(req){const value=req.headers['x-admin-password'];if(safeEqual(value,process.env.ADMIN_PASSWORD))return'admin';if(process.env.VIEWER_PASSWORD&&safeEqual(value,process.env.VIEWER_PASSWORD))return'viewer';return null}
function body(req){return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{})}
const SUPABASE_TIMEOUT_MS=Math.min(15000,Math.max(12000,Number(process.env.SUPABASE_TIMEOUT_MS)||15000));
const SUPABASE_STORAGE_TIMEOUT_MS=Math.min(30000,Math.max(12000,Number(process.env.SUPABASE_STORAGE_TIMEOUT_MS)||20000));
function isUpstreamStatus(status){return [502,503,504].includes(Number(status))}
function upstreamFailure(status=503,code='UPSTREAM_UNAVAILABLE',message='Không thể tải dữ liệu.'){return Object.assign(new Error(message),{status,code,retryable:true})}
async function upstreamJson(url,options={},timeoutMs=SUPABASE_TIMEOUT_MS,kind='data'){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs),externalSignal=options.signal,abortExternal=()=>controller.abort();
 if(externalSignal){if(externalSignal.aborted)controller.abort();else externalSignal.addEventListener('abort',abortExternal,{once:true})}
 try{
  const response=await fetch(url,{...options,signal:controller.signal}),text=await response.text();
  let data=null;if(text){try{data=JSON.parse(text)}catch{} }return{response,data};
 }catch(error){if(error?.name==='AbortError')throw upstreamFailure(504,'UPSTREAM_TIMEOUT',kind==='storage'?'Máy chủ lưu tệp phản hồi quá chậm.':'Máy chủ dữ liệu phản hồi quá chậm.');throw upstreamFailure(503,'UPSTREAM_UNAVAILABLE',kind==='storage'?'Không thể kết nối máy chủ lưu tệp.':'Không thể kết nối máy chủ dữ liệu.')}
 finally{clearTimeout(timer);externalSignal?.removeEventListener?.('abort',abortExternal)}
}
const DOCUMENT_RECOGNITION_TIMEOUT_MS=Math.min(25000,Math.max(15000,Number(process.env.DOCUMENT_OCR_TIMEOUT_MS)||20000));
const DOCUMENT_RECOGNITION_MAX_IMAGE_BYTES=3*1024*1024,DOCUMENT_RECOGNITION_MAX_TOTAL_BYTES=5*1024*1024;
const DOCUMENT_RECOGNITION_MIME_TYPES=new Set(['image/jpeg','image/png','image/webp']);
const DOCUMENT_RECOGNITION_TYPES=new Set(['cccd','passport']);
const DOCUMENT_COUNTRY_ALIASES=Object.freeze({'vietnam':'VN','viet nam':'VN','việt nam':'VN','russia':'RU','russian':'RU','russian federation':'RU','nga':'RU','south korea':'KR','korea':'KR','korean':'KR','hàn quốc':'KR','united states':'US','usa':'US','us':'US','hoa ky':'US','hoa kỳ':'US','japan':'JP','japanese':'JP','nhat ban':'JP','nhật bản':'JP','china':'CN','chinese':'CN','trung quoc':'CN','trung quốc':'CN','taiwan':'TW','đài loan':'TW','dai loan':'TW','united kingdom':'GB','uk':'GB','anh':'GB'});
const DOCUMENT_COUNTRY_ALPHA3=Object.freeze({VNM:'VN',RUS:'RU',KOR:'KR',USA:'US',GBR:'GB',JPN:'JP',CHN:'CN',TWN:'TW',THA:'TH',SGP:'SG',MYS:'MY',IDN:'ID',PHL:'PH',IND:'IN',DEU:'DE',FRA:'FR',CAN:'CA',AUS:'AU',NZL:'NZ',BRA:'BR',MEX:'MX',ARG:'AR',CHL:'CL',COL:'CO',PER:'PE',ESP:'ES',ITA:'IT',PRT:'PT',NLD:'NL',BEL:'BE',CHE:'CH',AUT:'AT',POL:'PL',CZE:'CZ',SVK:'SK',HUN:'HU',ROU:'RO',BGR:'BG',GRC:'GR',SWE:'SE',NOR:'NO',DNK:'DK',FIN:'FI',IRL:'IE',ZAF:'ZA',SAU:'SA',ARE:'AE',TUR:'TR',ISR:'IL',EGY:'EG',KAZ:'KZ',MNG:'MN',KHM:'KH',LAO:'LA',MMR:'MM',BGD:'BD',PAK:'PK',LKA:'LK',NPL:'NP'});
function recognitionError(message,status=400,code='DOCUMENT_RECOGNITION_ERROR'){return Object.assign(new Error(message),{status,code})}
function normalizeRecognitionText(value){const text=String(value??'').replace(/\s+/g,' ').trim();return text||null}
function normalizeRecognitionDate(value){const raw=normalizeRecognitionText(value);if(!raw)return null;const iso=/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/.exec(raw),dmy=/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})$/.exec(raw);if(!iso&&!dmy)return null;const year=Number(iso?iso[1]:dmy[3]),month=Number(iso?iso[2]:dmy[2]),day=Number(iso?iso[3]:dmy[1]),date=new Date(Date.UTC(year,month-1,day));return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day?`${String(year).padStart(4,'0')}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`:null}
function normalizeRecognitionIdentityNumber(value){const text=normalizeRecognitionText(value);return text?text.replace(/[\s<]/g,'').toUpperCase():null}
function normalizeRecognitionNationality(value){const text=normalizeRecognitionText(value);if(!text)return null;const code=text.toUpperCase();if(/^[A-Z]{2}$/.test(code))return code;if(/^[A-Z]{3}$/.test(code)&&DOCUMENT_COUNTRY_ALPHA3[code])return DOCUMENT_COUNTRY_ALPHA3[code];return DOCUMENT_COUNTRY_ALIASES[text.toLocaleLowerCase('vi')]||DOCUMENT_COUNTRY_ALIASES[text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('vi')]||null}
function normalizeRecognitionImages(documentType,images){const type=String(documentType||'').trim().toLocaleLowerCase('vi');if(!DOCUMENT_RECOGNITION_TYPES.has(type))throw recognitionError('Vui lòng chọn CCCD Việt Nam hoặc Hộ chiếu.',400,'DOCUMENT_TYPE_INVALID');if(!Array.isArray(images)||!images.length)throw recognitionError('Vui lòng chọn ảnh giấy tờ trước khi đọc thông tin.',400,'DOCUMENT_IMAGES_MISSING');if(images.length>2)throw recognitionError('Chỉ hỗ trợ tối đa 2 ảnh giấy tờ mỗi lần đọc.',400,'DOCUMENT_IMAGES_TOO_MANY');const seen=new Set(),normalized=[];let totalBytes=0;for(const item of images){const side=String(item?.side||'').trim().toLocaleLowerCase('vi'),allowed=type==='passport'?new Set(['main','front']):new Set(['front','back']);if(!allowed.has(side)||seen.has(side))throw recognitionError('Ảnh giấy tờ không hợp lệ.',400,'DOCUMENT_SIDE_INVALID');seen.add(side);const data=String(item?.data||''),match=/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=\s]+)$/i.exec(data),mime=String(match?.[1]||'').toLowerCase(),encoded=String(match?.[2]||'').replace(/\s/g,'');if(!match||!DOCUMENT_RECOGNITION_MIME_TYPES.has(mime)||!encoded||encoded.length%4===1||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))throw recognitionError('Ảnh giấy tờ không hợp lệ hoặc không đọc được.',400,'DOCUMENT_IMAGE_INVALID');const buffer=Buffer.from(encoded,'base64');if(!buffer.length||buffer.length>DOCUMENT_RECOGNITION_MAX_IMAGE_BYTES)throw recognitionError('Ảnh giấy tờ phải nhỏ hơn hoặc bằng 3 MB.',413,'DOCUMENT_IMAGE_TOO_LARGE');totalBytes+=buffer.length;if(totalBytes>DOCUMENT_RECOGNITION_MAX_TOTAL_BYTES)throw recognitionError('Tổng dung lượng ảnh giấy tờ phải nhỏ hơn hoặc bằng 5 MB.',413,'DOCUMENT_IMAGES_TOO_LARGE');normalized.push({side,mime,data:`data:${mime};base64,${encoded}`,size:buffer.length})}if(!seen.has(type==='passport'?'main':'front'))throw recognitionError(type==='passport'?'Vui lòng chọn trang thông tin hộ chiếu.':'Vui lòng chọn ảnh mặt trước CCCD.',400,'DOCUMENT_MAIN_IMAGE_MISSING');return{document_type:type,images:normalized}}
function recognitionFieldValue(fields,name){const field=fields?.[name];return field&&typeof field==='object'&&'value' in field?field.value:field}
function recognitionConfidence(fields,name){const field=fields?.[name],value=recognitionFieldValue(fields,name),confidence=field&&typeof field==='object'&&'confidence' in field?Number(field.confidence):value?0.8:0;return Number.isFinite(confidence)?Math.max(0,Math.min(1,confidence)):0}
function mrzCheckDigitValid(value,check){const digit=String(check||'');if(!/^\d$/.test(digit))return false;const weights=[7,3,1],chars=String(value||'').toUpperCase(),sum=[...chars].reduce((total,char,index)=>{const code=char==='<'?0:/\d/.test(char)?Number(char):char>='A'&&char<='Z'?char.charCodeAt(0)-55:0;return total+code*weights[index%3]},0);return sum%10===Number(digit)}
function passportMrzIsValid(line){const value=String(line||'');if(value.length<44)return null;return[mrzCheckDigitValid(value.slice(0,9),value[9]),mrzCheckDigitValid(value.slice(13,19),value[19]),mrzCheckDigitValid(value.slice(21,27),value[27]),mrzCheckDigitValid(value.slice(28,42),value[42]),mrzCheckDigitValid(value.slice(0,10)+value.slice(13,20)+value.slice(21,43),value[43])].every(Boolean)}
function parsePassportMrz(value){const source=Array.isArray(value)?value.join('\n'):String(value||'');const lines=source.toUpperCase().split(/\r?\n/).map(line=>line.replace(/\s/g,'')).filter(line=>line.length>=40&&/^[A-Z0-9<]+$/.test(line));if(lines.length<2)return null;const first=lines.find(line=>line.startsWith('P<'))||lines[0],second=lines.find(line=>line!==first&&line.length>=40)||lines[1],dateCode=second.slice(13,19),dateMatch=/^(\d{2})(\d{2})(\d{2})$/.exec(dateCode);let dateOfBirth=null;if(dateMatch){const yy=Number(dateMatch[1]),currentYear=Number(todayVN().slice(2,4)),year=yy<=currentYear?2000+yy:1900+yy;dateOfBirth=`${year}-${dateMatch[2]}-${dateMatch[3]}`;dateOfBirth=normalizeRecognitionDate(dateOfBirth)}const namePart=first.slice(5).replace(/<+/g,' ').trim();return{full_name:normalizeRecognitionText(namePart)||null,identity_number:normalizeRecognitionIdentityNumber(second.slice(0,9)),date_of_birth:dateOfBirth,nationality:normalizeRecognitionNationality(second.slice(10,13)),mrz_valid:passportMrzIsValid(second)}}
function normalizeRecognitionResult(documentType,providerResult){const rawFields=providerResult?.fields||{},fields={full_name:{value:normalizeRecognitionText(recognitionFieldValue(rawFields,'full_name')),confidence:recognitionConfidence(rawFields,'full_name')},identity_number:{value:normalizeRecognitionIdentityNumber(recognitionFieldValue(rawFields,'identity_number')),confidence:recognitionConfidence(rawFields,'identity_number')},date_of_birth:{value:normalizeRecognitionDate(recognitionFieldValue(rawFields,'date_of_birth')),confidence:recognitionConfidence(rawFields,'date_of_birth')},nationality:{value:normalizeRecognitionNationality(recognitionFieldValue(rawFields,'nationality')),confidence:recognitionConfidence(rawFields,'nationality')},permanent_address:{value:normalizeRecognitionText(recognitionFieldValue(rawFields,'permanent_address')),confidence:recognitionConfidence(rawFields,'permanent_address')}},warnings=[];if(documentType==='passport'){const mrz=parsePassportMrz(providerResult?.mrz);if(mrz){if(mrz.mrz_valid===false)warnings.push('Không thể xác thực đầy đủ vùng MRZ, vui lòng kiểm tra lại.');for(const name of ['full_name','identity_number','date_of_birth','nationality']){if(!mrz[name])continue;const previous=fields[name].value;if(previous&&previous!==mrz[name]){warnings.push('Thông tin trên vùng chữ và MRZ chưa khớp, vui lòng kiểm tra lại.');fields[name].confidence=Math.min(fields[name].confidence||0.8,.65)}fields[name].value=mrz[name];if(!previous)fields[name].confidence=Math.max(fields[name].confidence,.94)}}}const hasValue=Object.values(fields).some(field=>field.value);if(!hasValue)throw recognitionError('Không nhận diện được đầy đủ thông tin. Vui lòng chụp lại ảnh rõ hơn.',422,'DOCUMENT_NOT_RECOGNIZED');return{fields,warnings:[...new Set(warnings)]}}
const DOCUMENT_RECOGNITION_SCHEMA={type:'object',additionalProperties:false,properties:{fields:{type:'object',additionalProperties:false,properties:{full_name:{type:'object',additionalProperties:false,properties:{value:{type:['string','null']},confidence:{type:'number'}},required:['value','confidence']},identity_number:{type:'object',additionalProperties:false,properties:{value:{type:['string','null']},confidence:{type:'number'}},required:['value','confidence']},date_of_birth:{type:'object',additionalProperties:false,properties:{value:{type:['string','null']},confidence:{type:'number'}},required:['value','confidence']},nationality:{type:'object',additionalProperties:false,properties:{value:{type:['string','null']},confidence:{type:'number'}},required:['value','confidence']},permanent_address:{type:'object',additionalProperties:false,properties:{value:{type:['string','null']},confidence:{type:'number'}},required:['value','confidence']}},required:['full_name','identity_number','date_of_birth','nationality','permanent_address']},mrz:{type:['string','null']},warnings:{type:'array',items:{type:'string'}}},required:['fields','mrz','warnings']};
function extractProviderText(payload){if(typeof payload?.output_text==='string')return payload.output_text;for(const item of Array.isArray(payload?.output)?payload.output:[]){for(const content of Array.isArray(item?.content)?item.content:[])if(typeof content?.text==='string')return content.text}for(const choice of Array.isArray(payload?.choices)?payload.choices:[]){const content=choice?.message?.content;if(typeof content==='string')return content;if(Array.isArray(content)){const text=content.find(item=>typeof item?.text==='string')?.text;if(text)return text}}return''}
function parseProviderJson(text){const cleaned=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(cleaned)}catch{throw recognitionError('Không nhận diện được đầy đủ thông tin. Vui lòng chụp lại ảnh rõ hơn.',422,'DOCUMENT_PROVIDER_INVALID_RESPONSE')}}
function documentRecognitionPrompt(documentType){return`Bạn là bộ phận hỗ trợ nhập liệu hồ sơ cho Bloom Apartment. Đọc ảnh ${documentType==='passport'?'hộ chiếu':'CCCD Việt Nam'} và chỉ trả về JSON theo schema được cung cấp. Không đoán dữ liệu không nhìn thấy; trường không chắc chắn phải để null. Giữ nguyên cách viết hoa và thứ tự họ tên gần với giấy tờ. date_of_birth phải là YYYY-MM-DD. nationality phải là mã ISO alpha-2 viết hoa nếu đọc được. Với hộ chiếu, trích xuất toàn bộ MRZ vào trường mrz nếu nhìn thấy và ưu tiên kiểm tra MRZ. Không đưa ảnh, base64, văn bản OCR thô hoặc dữ liệu ngoài schema vào kết quả.`}
async function recognizeWithDocumentProvider(input){const key=String(process.env.DOCUMENT_OCR_API_KEY||'').trim();if(!key)throw recognitionError('Tính năng đọc thông tin chưa được cấu hình trên máy chủ.',503,'DOCUMENT_OCR_NOT_CONFIGURED');const endpoint=String(process.env.DOCUMENT_OCR_API_URL||'https://api.openai.com/v1/responses').trim();let url;try{url=new URL(endpoint)}catch{throw recognitionError('Tính năng đọc thông tin chưa được cấu hình trên máy chủ.',503,'DOCUMENT_OCR_CONFIG_INVALID')}if(!['http:','https:'].includes(url.protocol))throw recognitionError('Tính năng đọc thông tin chưa được cấu hình trên máy chủ.',503,'DOCUMENT_OCR_CONFIG_INVALID');const model=String(process.env.DOCUMENT_OCR_MODEL||'gpt-4.1-mini').trim(),content=[{type:'input_text',text:documentRecognitionPrompt(input.document_type)},...input.images.map(image=>({type:'input_image',image_url:image.data,detail:'high'}))],controller=new AbortController(),timer=setTimeout(()=>controller.abort(),DOCUMENT_RECOGNITION_TIMEOUT_MS);try{const response=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:[{role:'user',content}],temperature:0,max_output_tokens:900,text:{format:{type:'json_schema',name:'bloom_identity_document',strict:true,schema:DOCUMENT_RECOGNITION_SCHEMA}}}),signal:controller.signal});if(!response.ok)throw recognitionError('Nhà cung cấp nhận diện không khả dụng.',response.status>=500?503:502,'DOCUMENT_OCR_PROVIDER_HTTP');const payload=await response.json().catch(()=>null),text=extractProviderText(payload);if(!text)throw recognitionError('Không nhận diện được đầy đủ thông tin. Vui lòng chụp lại ảnh rõ hơn.',422,'DOCUMENT_PROVIDER_EMPTY');return parseProviderJson(text)}catch(error){if(error?.code?.startsWith('DOCUMENT_'))throw error;if(error?.name==='AbortError')throw recognitionError('Không thể đọc thông tin từ ảnh. Vui lòng thử lại.',504,'DOCUMENT_OCR_TIMEOUT');throw recognitionError('Không thể đọc thông tin từ ảnh. Vui lòng thử lại.',503,'DOCUMENT_OCR_NETWORK')}finally{clearTimeout(timer)}}
async function recognizeIdentityDocument(input){return normalizeRecognitionResult(input.document_type,await recognizeWithDocumentProvider(input))}
function required(obj,fields){for(const f of fields)if(obj[f]===undefined||obj[f]===null||obj[f]==='')throw Object.assign(new Error(`Thiếu trường ${f}`),{status:400})}
function number(v,name){const n=Number(v);if(!Number.isFinite(n)||n<0)throw Object.assign(new Error(`${name} không hợp lệ`),{status:400});return n}
async function db(path,options={}){const base=(process.env.SUPABASE_URL||'').replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw upstreamFailure(503,'UPSTREAM_NOT_CONFIGURED','Chưa cấu hình Supabase');const {response:r,data}=await upstreamJson(`${base}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json',...(options.headers||{})}},SUPABASE_TIMEOUT_MS,'data');if(!r.ok){if(isUpstreamStatus(r.status))throw upstreamFailure(Number(r.status)===504?504:503,Number(r.status)===504?'UPSTREAM_TIMEOUT':'UPSTREAM_UNAVAILABLE');throw Object.assign(new Error(data?.message||data?.hint||'Lỗi database'),{status:r.status,code:data?.code,retryable:false})}return data}
function normalizeRoomNumber(value){return String(value??'').trim().toLocaleLowerCase('vi')}
function isRoomConflictError(error){return Number(error?.status)===409||String(error?.code||'')==='23505'||/(23505|duplicate key|unique constraint|duplicate object)/i.test(String(error?.message||''))}
async function ensureUniqueRoomNumber(propertyId,roomNumber,excludeId=''){const normalized=normalizeRoomNumber(roomNumber);if(!normalized)throw Object.assign(new Error('Vui lòng nhập số phòng.'),{status:400});const rooms=await db(`rooms?property_id=eq.${encodeURIComponent(propertyId)}&select=id,room_number`);if(rooms.some(room=>String(room.id)!==String(excludeId||'')&&normalizeRoomNumber(room.room_number)===normalized))throw Object.assign(new Error('Phòng này đã tồn tại.'),{status:409})}
const DOCUMENT_BUCKET='private-documents',MAX_DOCUMENT_BYTES=3*1024*1024;
async function storageRequest(path,options={}){const base=(process.env.SUPABASE_URL||'').replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw upstreamFailure(503,'UPSTREAM_NOT_CONFIGURED','Chưa cấu hình Supabase Storage');const {response:r,data}=await upstreamJson(`${base}/storage/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json',...(options.headers||{})}},SUPABASE_STORAGE_TIMEOUT_MS,'storage');if(!r.ok){if(isUpstreamStatus(r.status))throw upstreamFailure(Number(r.status)===504?504:503,Number(r.status)===504?'UPSTREAM_TIMEOUT':'UPSTREAM_UNAVAILABLE');throw Object.assign(new Error(data?.message||data?.error||'Lỗi lưu tệp'),{status:r.status,code:data?.code,retryable:false})}return data}
async function signedDocumentUrls(paths){if(!paths.length)return{};const data=await storageRequest(`object/sign/${DOCUMENT_BUCKET}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paths,expiresIn:3600})});const base=(process.env.SUPABASE_URL||'').replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');return Object.fromEntries((data||[]).map(x=>[x.path,x.signedURL?.startsWith('http')?x.signedURL:`${base}/storage/v1${x.signedURL||''}`]))}
async function hydrateDocumentLinks(rows,resource){const pathField=resource==='tenants'?'identity_document_path':'contract_document_path',urlField=resource==='tenants'?'identity_document_url':'contract_document_url',paths=[...new Set(rows.map(x=>x[pathField]).filter(Boolean))];if(!paths.length)return rows.map(x=>({...x,[urlField]:null}));const urls=await signedDocumentUrls(paths);return rows.map(x=>({...x,[urlField]:x[pathField]?urls[x[pathField]]||null:null}))}
const DOCUMENT_ENTITY_CONFIG={tenant:{table:'tenants',legacyField:'identity_document_path',legacyType:'identity'},lease:{table:'leases',legacyField:'contract_document_path',legacyType:'contract'}};
const DOCUMENT_MIME_EXTENSIONS={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
const DOCUMENT_TYPE_OPTIONS={tenant:new Set(['identity_front','identity_back','passport','visa','residence','other','identity']),lease:new Set(['contract','appendix','handover','deposit_receipt','other'])};
function documentConfig(entityType){const config=DOCUMENT_ENTITY_CONFIG[String(entityType||'')];if(!config)throw Object.assign(new Error('Loại hồ sơ tài liệu không hợp lệ'),{status:400});return config}
function documentFilename(value,fallback='tai-lieu'){const name=String(value||'').split(/[\\/]/).pop().trim();return(name||fallback).slice(0,255)}
function documentType(entityType,value){const type=String(value||'').trim();if(!type)return documentConfig(entityType).legacyType;if(!DOCUMENT_TYPE_OPTIONS[entityType]?.has(type))throw Object.assign(new Error('Loại tài liệu không hợp lệ'),{status:400});return type}
async function findDocumentEntity(entityType,entityId,propertyId=''){const config=documentConfig(entityType),propertyFilter=propertyId?`&property_id=eq.${encodeURIComponent(propertyId)}`:'';return(await db(`${config.table}?id=eq.${encodeURIComponent(entityId)}${propertyFilter}&select=id,property_id,${config.legacyField}`))[0]||null}
async function hydrateDocumentAttachments(rows){const paths=[...new Set(rows.map(x=>x.file_path).filter(Boolean))],urls=paths.length?await signedDocumentUrls(paths):{};return rows.map(x=>({...x,signed_url:x.file_path?urls[x.file_path]||null:null}))}
async function getDocumentAttachments(entityType,entityId,propertyId=''){const config=documentConfig(entityType),entity=await findDocumentEntity(entityType,entityId,propertyId);if(!entity)throw Object.assign(new Error('Không tìm thấy hồ sơ hoặc hồ sơ không thuộc tòa nhà đã chọn'),{status:404});let rows=[];try{rows=await db(`document_attachments?property_id=eq.${encodeURIComponent(entity.property_id)}&entity_type=eq.${encodeURIComponent(entityType)}&entity_id=eq.${encodeURIComponent(entityId)}&select=id,property_id,entity_type,entity_id,document_type,file_path,file_name,mime_type,file_size,sort_order,created_at,updated_at&order=sort_order.asc,created_at.asc`)}catch(error){if(!/document_attachments/i.test(error.message||''))throw error}const legacyPath=entity[config.legacyField];if(legacyPath&&!rows.some(x=>x.file_path===legacyPath))rows.unshift({id:null,property_id:entity.property_id,entity_type:entityType,entity_id:entityId,document_type:config.legacyType,file_path:legacyPath,file_name:null,mime_type:null,file_size:null,sort_order:-1,created_at:null,updated_at:null,legacy:true});return hydrateDocumentAttachments(rows)}
async function hydrateDocumentSummary(rows,resource){const entityType=resource==='tenants'?'tenant':'lease',pathField=entityType==='tenant'?'identity_document_path':'contract_document_path',withLegacy=await hydrateDocumentLinks(rows,resource),ids=rows.map(x=>x.id).filter(Boolean);if(!ids.length)return withLegacy.map(x=>({...x,document_count:x[pathField]?1:0}));const propertyId=rows.find(x=>x.property_id)?.property_id;let attachments=[];if(propertyId){try{attachments=await db(`document_attachments?property_id=eq.${encodeURIComponent(propertyId)}&entity_type=eq.${entityType}&${listFilter('entity_id',ids)}&select=entity_id,file_path`)}catch(error){if(!/document_attachments/i.test(error.message||''))throw error}}const byEntity={};for(const attachment of attachments)(byEntity[attachment.entity_id]??=[]).push(attachment.file_path);return withLegacy.map(row=>{const paths=new Set(byEntity[row.id]||[]);if(row[pathField])paths.add(row[pathField]);return {...row,document_count:paths.size}})}
async function removeDocumentStorage(filePath){if(!filePath)return true;try{await storageRequest('object/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefixes:[filePath]})});return true}catch(error){console.error('document storage delete',error.message);return false}}
async function audit(action,type,id,details){try{await db('audit_logs',{method:'POST',body:JSON.stringify({action,entity_type:type,entity_id:String(id||''),details})})}catch(e){console.error('audit',e.message)}}
async function attachRoomNumbers(rows,propertyId=''){if(!rows.length)return rows;const filter=propertyId?`property_id=eq.${encodeURIComponent(propertyId)}&`:'';const rooms=await db(`rooms?${filter}select=id,room_number`);const byId=Object.fromEntries(rooms.map(r=>[r.id,{room_number:r.room_number}]));return rows.map(r=>({...r,rooms:byId[r.room_id]||null}))}
async function hydrateRooms(rows){if(!rows.length)return rows;const roomIds=rows.map(x=>x.id).join(','),leases=await db(`leases?room_id=in.(${roomIds})&select=room_id,monthly_rent,start_date,end_date,status&order=start_date.desc`),rentByRoom={},occupiedRoomIds=new Set();for(const lease of leases)if(effectiveLeaseStatus(lease)==='active'){occupiedRoomIds.add(lease.room_id);if(rentByRoom[lease.room_id]===undefined)rentByRoom[lease.room_id]=lease.monthly_rent}return rows.map(row=>({...row,effective_status:effectiveRoomStatus(row,occupiedRoomIds),actual_rent:rentByRoom[row.id]??null}))}
async function hydrateTenants(rows){if(!rows.length)return rows;const tenantIds=rows.map(x=>x.id).join(','),[links,representativeLeases]=await Promise.all([db(`lease_tenants?tenant_id=in.(${tenantIds})&select=tenant_id,lease_id,is_representative,move_in_date,move_out_date`),db(`leases?representative_tenant_id=in.(${tenantIds})&select=id,representative_tenant_id,start_date,end_date,status`)]);const leaseIds=[...new Set(links.map(x=>x.lease_id).filter(Boolean))].join(','),linkedLeases=leaseIds?await db(`leases?id=in.(${leaseIds})&select=id,start_date,end_date,status`):[],leaseById=Object.fromEntries([...linkedLeases,...representativeLeases].map(x=>[x.id,x])),relations={};for(const link of links){const lease=leaseById[link.lease_id];if(lease)(relations[link.tenant_id]??=[]).push({...lease,move_in_date:link.move_in_date,move_out_date:link.move_out_date})}for(const lease of representativeLeases)(relations[lease.representative_tenant_id]??=[]).push(lease);return rows.map(row=>{const items=relations[row.id]||[],lease=items.find(x=>leaseIsCurrent(x))||items.sort((a,b)=>String(b.start_date||'').localeCompare(String(a.start_date||'')))[0],leaseStatus=lease?effectiveLeaseStatus(lease):null;return {...row,rental_start_date:lease?.move_in_date||lease?.start_date||null,rental_status:leaseStatus==='active'?'active':'ended'}})}
async function syncRoomStatuses(propertyId){if(!propertyId)return;const filter=`property_id=eq.${encodeURIComponent(propertyId)}`;const [rooms,leases]=await Promise.all([db(`rooms?${filter}&select=id,status`),db(`leases?${filter}&select=room_id,status,start_date,end_date`)]);const occupied=new Set(leases.filter(leaseIsCurrent).map(x=>x.room_id)),toOccupied=rooms.filter(r=>r.status==='vacant'&&occupied.has(r.id)),toVacant=rooms.filter(r=>r.status==='occupied'&&!occupied.has(r.id));await Promise.all([toOccupied.length?db(`rooms?id=in.(${toOccupied.map(r=>encodeURIComponent(r.id)).join(',')})`,{method:'PATCH',body:JSON.stringify({status:'occupied'})}):Promise.resolve([]),toVacant.length?db(`rooms?id=in.(${toVacant.map(r=>encodeURIComponent(r.id)).join(',')})`,{method:'PATCH',body:JSON.stringify({status:'vacant'})}):Promise.resolve([])])}
function previousPeriod(period){const match=/^(\d{4})-(\d{2})$/.exec(String(period||''));if(!match)return null;const date=new Date(Date.UTC(Number(match[1]),Number(match[2])-2,1));return`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`}
async function previousDebtStateByRoom(propertyId,period,roomIds=[]){
 if(!propertyId||!period)return{};
 const previous=previousPeriod(period);if(!previous)return{};
 const property=encodeURIComponent(propertyId),previousPeriods=await db(`billing_periods?property_id=eq.${property}&period=eq.${encodeURIComponent(previous)}&select=id`),periodIds=previousPeriods.map(x=>x.id);
 if(!periodIds.length)return{};
 const roomFilter=roomIds.length?`&room_id=in.(${roomIds.join(',')})`:'';
 const records=await db(`monthly_room_records?property_id=eq.${property}&billing_period_id=in.(${periodIds.join(',')})${roomFilter}&select=id,room_id`),recordIds=records.map(x=>x.id);
 if(!recordIds.length)return{};
 const invoices=await db(`invoices?record_id=in.(${recordIds.join(',')})&status=neq.cancelled&select=id,record_id,total_amount,paid_amount`),invoiceIds=invoices.map(x=>x.id),payments=invoiceIds.length?await db(`payments?invoice_id=in.(${invoiceIds.join(',')})&select=invoice_id,amount`):[];
 const paidByInvoice=payments.reduce((m,x)=>(m[x.invoice_id]=(m[x.invoice_id]||0)+Number(x.amount||0),m),{}),roomByRecord=Object.fromEntries(records.map(x=>[x.id,x.room_id])),state={};
 for(const invoice of invoices){const roomId=roomByRecord[invoice.record_id];if(!roomId)continue;const paid=Math.max(Number(invoice.paid_amount||0),Number(paidByInvoice[invoice.id]||0)),remaining=Math.max(0,Number(invoice.total_amount||0)-paid),current=state[roomId]||{debt:0,hasInvoice:false};current.debt+=remaining;current.hasInvoice=true;state[roomId]=current}
 return state;
}
async function previousDebtByRoom(propertyId,period,roomIds=[]){const state=await previousDebtStateByRoom(propertyId,period,roomIds);return Object.fromEntries(Object.entries(state).map(([roomId,item])=>[roomId,item.debt]))}
async function previousElectricEndByRoom(propertyId,period,roomIds=[]){if(!propertyId||!period)return{};const previous=previousPeriod(period);if(!previous)return{};const property=encodeURIComponent(propertyId),previousPeriods=await db(`billing_periods?property_id=eq.${property}&period=eq.${encodeURIComponent(previous)}&select=id`),periodIds=previousPeriods.map(x=>x.id);if(!periodIds.length)return{};const roomFilter=roomIds.length?`&room_id=in.(${roomIds.join(',')})`:'';const records=await db(`monthly_room_records?property_id=eq.${property}&billing_period_id=in.(${periodIds.join(',')})${roomFilter}&select=room_id,electric_end`);return Object.fromEntries(records.map(x=>[x.room_id,Number(x.electric_end||0)]))}
async function hydrateInvoices(rows){if(!rows.length)return rows;const recordIds=rows.map(x=>x.record_id).join(',');const records=await db(`monthly_room_records?id=in.(${recordIds})&select=*`);const roomIds=[...new Set(records.map(x=>x.room_id).filter(Boolean))].join(',');const periodIds=[...new Set(records.map(x=>x.billing_period_id).filter(Boolean))].join(',');const leaseIds=[...new Set(records.map(x=>x.lease_id).filter(Boolean))].join(',');const [rooms,periods,leases]=await Promise.all([roomIds?db(`rooms?id=in.(${roomIds})&select=id,room_number`):[],periodIds?db(`billing_periods?id=in.(${periodIds})&select=id,period`):[],leaseIds?db(`leases?id=in.(${leaseIds})&select=id,representative_tenant_id`):[]]);const tenantIds=[...new Set(leases.map(x=>x.representative_tenant_id).filter(Boolean))].join(',');const tenants=tenantIds?await db(`tenants?id=in.(${tenantIds})&select=id,full_name`):[];const roomById=Object.fromEntries(rooms.map(x=>[x.id,x])),periodById=Object.fromEntries(periods.map(x=>[x.id,x])),tenantById=Object.fromEntries(tenants.map(x=>[x.id,x])),leaseById=Object.fromEntries(leases.map(x=>[x.id,{...x,tenants:tenantById[x.representative_tenant_id]||null}])),recordById=Object.fromEntries(records.map(x=>[x.id,{...x,rooms:roomById[x.room_id]||null,billing_periods:periodById[x.billing_period_id]||null,leases:leaseById[x.lease_id]||null}]));return rows.map(x=>({...x,monthly_room_records:recordById[x.record_id]||null}))}
async function hydrateInvoicePayments(rows){if(!rows.length)return rows;const ids=rows.map(x=>x.id).join(',');const payments=await db(`payments?invoice_id=in.(${ids})&select=invoice_id,amount,method`);const totals={};for(const p of payments){const item=totals[p.invoice_id]||{transfer:0,cash:0,total:0};const amount=Number(p.amount||0);item.total+=amount;if(p.method==='transfer')item.transfer+=amount;else if(p.method==='cash')item.cash+=amount;totals[p.invoice_id]=item}return rows.map(x=>{const t=totals[x.id]||{transfer:0,cash:0,total:0};return {...x,paid_transfer:t.transfer,paid_cash:t.cash,paid_amount:t.total}})}
async function hydrateInvoiceRows(rows){const [withPayments,withDetails]=await Promise.all([hydrateInvoicePayments(rows),hydrateInvoices(rows)]),paymentsById=Object.fromEntries(withPayments.map(row=>[row.id,row]));return withDetails.map(row=>{const payment=paymentsById[row.id]||{};return {...row,paid_transfer:payment.paid_transfer||0,paid_cash:payment.paid_cash||0,paid_amount:payment.paid_amount||0}})}
function sortInvoicesByRoom(rows){const collator=new Intl.Collator('vi',{numeric:true,sensitivity:'base'});return rows.sort((a,b)=>{const roomA=String(a.monthly_room_records?.rooms?.room_number||'').trim(),roomB=String(b.monthly_room_records?.rooms?.room_number||'').trim();if(!roomA&&!roomB)return 0;if(!roomA)return 1;if(!roomB)return-1;return collator.compare(roomA,roomB)})}
async function invoicesForPeriod(propertyId,period){const property=encodeURIComponent(propertyId),periodRows=await db(`billing_periods?property_id=eq.${property}&period=eq.${encodeURIComponent(period)}&select=id`);if(!periodRows.length)return[];const records=await db(`monthly_room_records?property_id=eq.${property}&billing_period_id=eq.${encodeURIComponent(periodRows[0].id)}&select=id`),recordIds=records.map(x=>x.id);if(!recordIds.length)return[];return db(`invoices?property_id=eq.${property}&record_id=in.(${recordIds.join(',')})&status=neq.cancelled&select=*&order=issued_at.desc`)}
async function hydrateLeases(rows){if(!rows.length)return rows;const leaseIds=rows.map(x=>x.id).join(','),links=await db(`lease_tenants?lease_id=in.(${leaseIds})&select=lease_id,tenant_id,is_representative,move_in_date,move_out_date`),tenantIds=[...new Set([...links.map(x=>x.tenant_id),...rows.map(x=>x.representative_tenant_id).filter(Boolean)])].join(',');const tenants=tenantIds?await db(`tenants?id=in.(${tenantIds})&select=id,full_name,identity_number,phone,permanent_address`):[];const tenantById=Object.fromEntries(tenants.map(x=>[x.id,x]));const linksByLease={};for(const link of links){(linksByLease[link.lease_id]??=[]).push({...link,tenant:tenantById[link.tenant_id]||null})}return rows.map(row=>{const occupants=linksByLease[row.id]||[];if(row.representative_tenant_id&&!occupants.some(x=>x.tenant_id===row.representative_tenant_id))occupants.unshift({lease_id:row.id,tenant_id:row.representative_tenant_id,is_representative:true,tenant:tenantById[row.representative_tenant_id]||row.tenants||null});return {...row,effective_status:effectiveLeaseStatus(row),occupants,occupant_ids:occupants.map(x=>x.tenant_id)}})}
async function syncLeaseOccupants(leaseId,propertyId,occupantIds=[],representativeId=null){if(!leaseId||!propertyId)return;const ids=[...new Set([representativeId,...(Array.isArray(occupantIds)?occupantIds:[])].filter(Boolean))];await db(`lease_tenants?lease_id=eq.${encodeURIComponent(leaseId)}`,{method:'DELETE'});if(ids.length)await db('lease_tenants',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(ids.map(tenantId=>({lease_id:leaseId,property_id:propertyId,tenant_id:tenantId,is_representative:tenantId===representativeId})))});}
function reportBounds(period){const [year,month]=String(period).split('-').map(Number);if(!year||!month||month<1||month>12)throw Object.assign(new Error('Kỳ báo cáo không hợp lệ'),{status:400});const start=new Date(`${String(year).padStart(4,'0')}-${String(month).padStart(2,'0')}-01T00:00:00+07:00`),nextMonth=month===12?1:month+1,nextYear=month===12?year+1:year,end=new Date(`${String(nextYear).padStart(4,'0')}-${String(nextMonth).padStart(2,'0')}-01T00:00:00+07:00`);return{start:start.toISOString(),end:end.toISOString()}}
function reportStatus(paid,total){if(paid<=0)return'unpaid';if(paid<total)return'partial';return'paid'}
function reportMethod(method){return method==='transfer'?'Chuyển khoản':method==='cash'?'Tiền mặt':method==='other'?'Khác':method||'—'}
function listFilter(field,values){const items=[...new Set(values.map(x=>String(x??'').trim()).filter(Boolean))];if(!items.length)return'';if(items.length===1)return`${field}=eq.${encodeURIComponent(items[0])}`;return`${field}=in.(${items.map(x=>encodeURIComponent(x)).join(',')})`}
async function buildReport(propertyId,period,mode='invoice'){
 const propertyIdEncoded=encodeURIComponent(propertyId),property=(await db(`properties?id=eq.${propertyIdEncoded}&select=id,name,property_code`))[0];
 if(!property)throw Object.assign(new Error('Không tìm thấy tòa nhà'),{status:404});
 const [rooms,leases]=await Promise.all([
  db(`rooms?property_id=eq.${propertyIdEncoded}&select=id,room_number,status`),
  db(`leases?property_id=eq.${propertyIdEncoded}&select=id,room_id,representative_tenant_id,start_date,end_date,status`)
 ]);
 const occupiedRoomIds=new Set(leases.filter(leaseIsCurrent).map(x=>x.room_id));
 let invoices=[],records=[],selectedPayments=[];
 if(mode==='cash'){
  const bounds=reportBounds(period);
  selectedPayments=await db(`payments?paid_at=gte.${encodeURIComponent(bounds.start)}&paid_at=lt.${encodeURIComponent(bounds.end)}&select=id,invoice_id,amount,paid_at,method&order=paid_at.desc`);
  const selectedInvoiceIds=[...new Set(selectedPayments.map(x=>x.invoice_id).filter(Boolean))];
  invoices=selectedInvoiceIds.length?await db(`invoices?property_id=eq.${propertyIdEncoded}&${listFilter('id',selectedInvoiceIds)}&status=neq.cancelled&select=id,record_id,total_amount,status`):[];
  const recordIds=invoices.map(x=>x.record_id).filter(Boolean);
  records=recordIds.length?await db(`monthly_room_records?property_id=eq.${propertyIdEncoded}&${listFilter('id',recordIds)}&select=*`):[];
 }else{
  const periods=await db(`billing_periods?property_id=eq.${propertyIdEncoded}&period=eq.${encodeURIComponent(period)}&select=id,period`),periodId=periods[0]?.id;
  if(periodId){
   records=await db(`monthly_room_records?property_id=eq.${propertyIdEncoded}&billing_period_id=eq.${encodeURIComponent(periodId)}&select=*`);
   const recordIds=records.map(x=>x.id);
   invoices=recordIds.length?await db(`invoices?property_id=eq.${propertyIdEncoded}&${listFilter('record_id',recordIds)}&status=neq.cancelled&select=id,record_id,total_amount,status`):[];
  }
 }
 const invoiceIds=invoices.map(x=>x.id),recordById=Object.fromEntries(records.map(x=>[x.id,x])),allPayments=invoiceIds.length?await db(`payments?${listFilter('invoice_id',invoiceIds)}&select=id,invoice_id,amount,paid_at,method&order=paid_at.desc`):[],paymentsByInvoice={};
 for(const payment of allPayments)(paymentsByInvoice[payment.invoice_id]??=[]).push(payment);
 const selectedByInvoice={};for(const payment of selectedPayments)(selectedByInvoice[payment.invoice_id]??=[]).push(payment);
 const recordPeriodIds=[...new Set(records.map(x=>x.billing_period_id).filter(Boolean))],periods=recordPeriodIds.length?await db(`billing_periods?property_id=eq.${propertyIdEncoded}&${listFilter('id',recordPeriodIds)}&select=id,period`):[],periodById=Object.fromEntries(periods.map(x=>[x.id,x.period]));
 // Báo cáo chỉ lấy người đại diện của hợp đồng đang có hiệu lực hiện tại.
 // Không dùng lease_id lịch sử trong monthly_room_records để xác định khách thuê.
 const activeLeaseByRoom={};
 for(const lease of leases){
  if(!leaseIsCurrent(lease)||activeLeaseByRoom[lease.room_id])continue;
  activeLeaseByRoom[lease.room_id]=lease;
 }
 const reportRoomIds=new Set(records.map(x=>x.room_id).filter(Boolean));
 const tenantIds=[...new Set(Object.values(activeLeaseByRoom).filter(x=>reportRoomIds.has(x.room_id)).map(x=>x.representative_tenant_id).filter(Boolean))];
 const tenants=tenantIds.length?await db(`tenants?property_id=eq.${propertyIdEncoded}&${listFilter('id',tenantIds)}&select=id,full_name`):[];
 const tenantById=Object.fromEntries(tenants.map(x=>[x.id,x])),roomById=Object.fromEntries(rooms.map(x=>[x.id,x]));
 const rows=invoices.map(invoice=>{
  const record=recordById[invoice.record_id];if(!record)return null;
  const all=paymentsByInvoice[invoice.id]||[],relevant=mode==='cash'?(selectedByInvoice[invoice.id]||[]):all,total=Number(invoice.total_amount||0),paidAll=all.reduce((sum,x)=>sum+Number(x.amount||0),0),paid=relevant.reduce((sum,x)=>sum+Number(x.amount||0),0),room=roomById[record.room_id],activeLease=activeLeaseByRoom[record.room_id],tenant=tenantById[activeLease?.representative_tenant_id],electric=Math.max(0,Number(record.electric_end||0)-Number(record.electric_start||0))*Number(record.electric_rate||0),water=Math.max(0,Number(record.water_end||0)-Number(record.water_start||0))*Number(record.water_rate||0),latest=relevant.slice().sort((a,b)=>String(b.paid_at||'').localeCompare(String(a.paid_at||'')))[0],methods=[...new Set(relevant.map(x=>reportMethod(x.method)))];
  return{invoice_id:invoice.id,property_name:property.name,property_code:property.property_code,room_id:record.room_id,room_number:room?.room_number||'—',tenant_name:tenant?.full_name||'—',period:periodById[record.billing_period_id]||period,rent_amount:Number(record.rent||0),electricity_amount:electric,water_amount:water,service_amount:Number(record.service_fee||0),other_amount:Number(record.other_fee||0),previous_debt:Number(record.previous_debt||0),discount_amount:Number(record.discount||0),total_amount:total,paid_amount:paid,paid_total:paidAll,debt_amount:Math.max(0,total-paidAll),payment_status:reportStatus(paidAll,total),latest_payment_at:latest?.paid_at||null,payment_method:methods.join(', ')||'—'};
 }).filter(Boolean);
 const totals=rows.reduce((sum,row)=>{for(const key of ['rent_amount','electricity_amount','water_amount','service_amount','other_amount','previous_debt','discount_amount','total_amount','paid_amount','debt_amount'])sum[key]=(sum[key]||0)+Number(row[key]||0);return sum},{});
 return{property,period,mode,rooms:{total:rooms.length,occupied:rooms.filter(x=>effectiveRoomStatus(x,occupiedRoomIds)==='occupied').length,vacant:rooms.filter(x=>effectiveRoomStatus(x,occupiedRoomIds)==='vacant').length},totals,rows}
}
function reportRecentPeriods(period,count=6){const [year,month]=String(period).split('-').map(Number),result=[];for(let i=count-1;i>=0;i--){const date=new Date(year,month-1-i,1),y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0');result.push(`${y}-${m}`)}return result}
async function buildReportTrendSafe(propertyId,period,mode){const periods=reportRecentPeriods(period,6),encoded=encodeURIComponent(propertyId);if(mode==='cash'){const first=reportBounds(periods[0]),last=reportBounds(periods[periods.length-1]),propertyInvoices=await db(`invoices?property_id=eq.${encoded}&status=neq.cancelled&select=id`),invoiceIds=propertyInvoices.map(x=>x.id),payments=invoiceIds.length?await db(`payments?${listFilter('invoice_id',invoiceIds)}&paid_at=gte.${encodeURIComponent(first.start)}&paid_at=lt.${encodeURIComponent(last.end)}&select=amount,paid_at`):[],byPeriod=Object.fromEntries(periods.map(x=>[x,0]));for(const payment of payments){const date=new Date(payment.paid_at),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit'}).formatToParts(date),key=`${parts.find(x=>x.type==='year').value}-${parts.find(x=>x.type==='month').value}`;if(key in byPeriod)byPeriod[key]+=Number(payment.amount||0)}return periods.map(x=>({period:x,total:0,paid:byPeriod[x]||0}))}const periodRows=await db(`billing_periods?property_id=eq.${encoded}&${listFilter('period',periods)}&select=id,period`),periodById=Object.fromEntries(periodRows.map(x=>[x.id,x.period])),periodIds=periodRows.map(x=>x.id),records=periodIds.length?await db(`monthly_room_records?property_id=eq.${encoded}&${listFilter('billing_period_id',periodIds)}&select=id,billing_period_id`):[],recordById=Object.fromEntries(records.map(x=>[x.id,x.billing_period_id])),recordIds=records.map(x=>x.id),invoices=recordIds.length?await db(`invoices?property_id=eq.${encoded}&${listFilter('record_id',recordIds)}&status=neq.cancelled&select=id,record_id,total_amount`):[],invoiceIds=invoices.map(x=>x.id),payments=invoiceIds.length?await db(`payments?${listFilter('invoice_id',invoiceIds)}&select=invoice_id,amount`):[],paidByInvoice={};for(const payment of payments)paidByInvoice[payment.invoice_id]=(paidByInvoice[payment.invoice_id]||0)+Number(payment.amount||0);const totals=Object.fromEntries(periods.map(x=>[x,{total:0,paid:0}]));for(const invoice of invoices){const key=periodById[recordById[invoice.record_id]];if(key){totals[key].total+=Number(invoice.total_amount||0);totals[key].paid+=paidByInvoice[invoice.id]||0}}return periods.map(x=>({period:x,total:totals[x].total,paid:totals[x].paid}))}
const maps={
 properties:{table:'properties',select:'*,property_settings(*),rooms(count)',order:'name.asc',required:['name'],allowed:['property_code','name','short_name','address','phone','owner_name','owner_phone','email','tax_code','total_floors','notes']},
 settings:{table:'property_settings',order:'created_at.asc',required:['property_id'],allowed:['property_id','electric_rate','water_rate','default_service_fee','billing_close_day','payment_due_day','bank_name','bank_bin','bank_account','bank_account_name','qr_template','invoice_note']},
 rooms:{table:'rooms',order:'room_number.asc',required:['property_id','room_number'],allowed:['property_id','room_number','floor','area','base_rent','status','notes']},
 tenants:{table:'tenants',order:'full_name.asc',required:['property_id','full_name'],allowed:['property_id','full_name','phone','email','nationality','identity_type','identity_number','date_of_birth','permanent_address','emergency_contact','notes']},
 leases:{table:'leases',select:'*,rooms!leases_room_id_fkey(room_number),tenants!leases_representative_tenant_id_fkey(full_name,phone)',order:'end_date.asc',required:['property_id','room_id','start_date','end_date'],allowed:['property_id','room_id','representative_tenant_id','start_date','end_date','monthly_rent','service_water_fee','deposit_amount','payment_due_day','status','ended_at','end_reason','deposit_refunded','notes']},
 visas:{table:'tenant_visas',select:'*,tenants!tenant_visas_tenant_id_fkey(full_name,nationality,phone)',order:'expiry_date.asc',required:['property_id','tenant_id','expiry_date'],allowed:['property_id','tenant_id','visa_number','visa_type','issued_date','expiry_date','issuing_country','document_url','status','notes']},
 invoices:{table:'invoices',select:'*',order:'issued_at.desc',required:['record_id'],allowed:['record_id','property_id','invoice_number','issued_at','due_date','total_amount','paid_amount','status','locked_at','cancelled_at','cancel_reason']}
};
function pick(input,fields){return Object.fromEntries(fields.filter(k=>input[k]!==undefined).map(k=>[k,input[k]]))}
function clean(row){const nullable=new Set(['representative_tenant_id','lease_id','date_of_birth','ended_at','issued_date','due_date']);const numeric=new Set(['floor','area','base_rent','total_floors','monthly_rent','service_water_fee','deposit_amount','payment_due_day','deposit_refunded','electric_rate','water_rate','default_service_fee','billing_close_day']);for(const k of Object.keys(row))if(row[k]===''){if(nullable.has(k))row[k]=null;else if(numeric.has(k))delete row[k]}return row}
function days(date){return Math.ceil((new Date(`${date}T00:00:00`)-new Date(new Date().toISOString().slice(0,10)+'T00:00:00'))/86400000)}
function warning(d){return d<0?'expired':d<=7?'danger':d<=30?'urgent':d<=60?'warning':'safe'}
function todayVN(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}).format(new Date())}
function effectiveLeaseStatus(lease){if(lease?.status==='terminated')return'terminated';const today=todayVN(),start=String(lease?.start_date||'').slice(0,10),end=String(lease?.end_date||'').slice(0,10);return start&&end&&start<=today&&today<=end?'active':'expired'}
function leaseIsCurrent(lease){return effectiveLeaseStatus(lease)==='active'}
const leaseSnapshotSelect='id,property_id,room_id,monthly_rent,service_water_fee,start_date,end_date,status';
function normalizeLeaseMoney(row){for(const [field,label] of [['monthly_rent','Tiền thuê'],['service_water_fee','Phí dịch vụ + nước'],['deposit_amount','Tiền cọc'],['deposit_refunded','Tiền cọc đã hoàn'],['payment_due_day','Ngày hạn thanh toán']])if(row[field]!==undefined)row[field]=number(row[field],label);return row}
function effectiveRoomStatus(room,occupiedRoomIds){if(['maintenance','reserved'].includes(room.status))return room.status;return occupiedRoomIds.has(room.id)?'occupied':'vacant'}
function invoiceHasPayment(invoice){return Number(invoice?.paid_amount||0)>0||['partial','paid'].includes(invoice?.status)}
function recordTotal(record){const electric=(Number(record.electric_end||0)-Number(record.electric_start||0))*Number(record.electric_rate||0),water=(Number(record.water_end||0)-Number(record.water_start||0))*Number(record.water_rate||0);return Math.max(0,Number(record.rent||0)+electric+water+Number(record.service_fee||0)+Number(record.other_fee||0)+Number(record.previous_debt||0)-Number(record.discount||0))}

module.exports=async function handler(req,res){
 const requestId=crypto.randomBytes(6).toString('hex'),startedAt=Date.now();let resource='dashboard';
 const userRole=role(req);if(!userRole)return reply(res,401,{error:'Mật khẩu không đúng'});
 try{
  resource=String(req.query.resource||'dashboard');
  if(req.method!=='GET'&&userRole!=='admin')return reply(res,403,{error:'Tài khoản chỉ có quyền xem'});
  if(req.method==='GET'&&resource==='session')return reply(res,200,{role:userRole});
   if(req.method==='POST'&&resource==='document-recognition'){
   const started=Date.now();let requestedType='unknown';
   try{
    const x=body(req);requestedType=String(x.document_type||'unknown').trim().toLocaleLowerCase('vi');
    const input=normalizeRecognitionImages(requestedType,x.images),result=await recognizeIdentityDocument(input);
     console.info('document-recognition',{requestId,type:requestedType,success:true,duration:Date.now()-started});
    return reply(res,200,{ok:true,document_type:input.document_type,fields:result.fields,warnings:result.warnings});
   }catch(error){
    const status=Number(error?.status)>=400&&Number(error?.status)<500?Number(error.status):error?.code==='DOCUMENT_OCR_NOT_CONFIGURED'||error?.code==='DOCUMENT_OCR_CONFIG_INVALID'?503:error?.code==='DOCUMENT_OCR_TIMEOUT'?504:503;
    const code=error?.code||'DOCUMENT_RECOGNITION_ERROR',message=code==='DOCUMENT_OCR_NOT_CONFIGURED'||code==='DOCUMENT_OCR_CONFIG_INVALID'?'Tính năng đọc thông tin chưa được cấu hình trên máy chủ.':status===400||status===413||status===422?error.message:'Không thể đọc thông tin từ ảnh. Vui lòng thử lại.';
     console.error('document-recognition',{requestId,type:requestedType,success:false,duration:Date.now()-started,status,code});
     return reply(res,status,{error:message,code,retryable:status>=500,requestId});
    }
   }
   if(resource==='document-recognition')return reply(res,405,{error:'Phương thức không được hỗ trợ'});
   if(req.method==='GET'&&resource==='dashboard'){
    const propertyId=String(req.query.property_id||''),from=String(req.query.from_period||''),to=String(req.query.to_period||'');if(from&&to&&from>to)throw Object.assign(new Error('Tháng bắt đầu không được lớn hơn tháng kết thúc'),{status:400});const filter=propertyId?`property_id=eq.${encodeURIComponent(propertyId)}&`:'';const periodFilter=(from?`&period=gte.${encodeURIComponent(from)}`:'')+(to?`&period=lte.${encodeURIComponent(to)}`:'');
     const [rooms,leases,visas,periods]=await Promise.all([db(`rooms?${filter}select=id,room_number,status`),db(`leases?${filter}select=id,room_id,representative_tenant_id,start_date,end_date,status`),db(`tenant_visas?${filter}status=eq.active&select=id,tenant_id,expiry_date`),propertyId?db(`billing_periods?property_id=eq.${encodeURIComponent(propertyId)}${periodFilter}&select=id,period`):[]]);
     const tenantIds=[...new Set(visas.map(x=>x.tenant_id).filter(Boolean))],tenantFilter=propertyId?`property_id=eq.${encodeURIComponent(propertyId)}&`:'';
     const currentLeases=leases.filter(leaseIsCurrent),occupiedRoomIds=new Set(currentLeases.map(x=>x.room_id)),currentLeaseIds=currentLeases.map(x=>x.id),leaseTenantFilter=propertyId?`property_id=eq.${encodeURIComponent(propertyId)}&`:'';
     const periodIds=periods.map(x=>x.id);
     const [visaTenants,records,leaseTenantLinks]=await Promise.all([
      tenantIds.length?db(`tenants?${tenantFilter}id=in.(${tenantIds.join(',')})&select=id,full_name`):[],
      periodIds.length?db(`monthly_room_records?property_id=eq.${encodeURIComponent(propertyId)}&billing_period_id=in.(${periodIds.join(',')})&select=id`):[],
      currentLeaseIds.length&&tenantIds.length?db(`lease_tenants?${leaseTenantFilter}lease_id=in.(${currentLeaseIds.join(',')})&tenant_id=in.(${tenantIds.join(',')})&select=lease_id,tenant_id`):[]
     ]);
     const roomById=Object.fromEntries(rooms.map(x=>[x.id,x])),tenantById=Object.fromEntries(visaTenants.map(x=>[x.id,x])),alertSort=new Intl.Collator('vi',{numeric:true,sensitivity:'base'}),recordIds=records.map(x=>x.id);
     const invoices=recordIds.length?await db(`invoices?record_id=in.(${recordIds.join(',')})&status=neq.cancelled&select=id,total_amount`):[],invoiceIds=invoices.map(x=>x.id);
     const payments=invoiceIds.length?await db(`payments?invoice_id=in.(${invoiceIds.join(',')})&select=invoice_id,amount`):[],paidByInvoice=payments.reduce((m,x)=>(m[x.invoice_id]=(m[x.invoice_id]||0)+Number(x.amount||0),m),{}),paid=payments.reduce((s,x)=>s+Number(x.amount||0),0),debt=invoices.reduce((s,x)=>s+Math.max(0,Number(x.total_amount||0)-Number(paidByInvoice[x.id]||0)),0),leaseById=Object.fromEntries(currentLeases.map(x=>[x.id,x])),tenantRooms={};
     for(const lease of currentLeases){const roomNumber=roomById[lease.room_id]?.room_number;if(roomNumber&&lease.representative_tenant_id)(tenantRooms[lease.representative_tenant_id]??=[]).push(String(roomNumber))}
     for(const link of leaseTenantLinks){const roomNumber=roomById[leaseById[link.lease_id]?.room_id]?.room_number;if(roomNumber)(tenantRooms[link.tenant_id]??=[]).push(String(roomNumber))}
     const leaseWarnings=currentLeases.filter(x=>x.end_date).map(x=>{const daysLeft=days(x.end_date);return{room_id:x.room_id,room_number:roomById[x.room_id]?.room_number||'—',end_date:x.end_date,days:daysLeft,level:warning(daysLeft)}}).filter(x=>x.days<=60).sort((a,b)=>a.days-b.days||alertSort.compare(String(a.room_number),String(b.room_number))),visaWarnings=visas.filter(x=>x.expiry_date).map(x=>{const daysLeft=days(x.expiry_date);return{tenant_id:x.tenant_id,tenant_name:tenantById[x.tenant_id]?.full_name||'—',room_number:[...new Set(tenantRooms[x.tenant_id]||[])].join(', ')||'—',expiry_date:x.expiry_date,days:daysLeft,level:warning(daysLeft)}}).filter(x=>x.days<=60).sort((a,b)=>a.days-b.days||alertSort.compare(String(a.tenant_name),String(b.tenant_name)));
     return reply(res,200,{period:{from:from||null,to:to||null},rooms:{total:rooms.length,occupied:rooms.filter(x=>effectiveRoomStatus(x,occupiedRoomIds)==='occupied').length,vacant:rooms.filter(x=>effectiveRoomStatus(x,occupiedRoomIds)==='vacant').length},paid,debt,leaseWarnings,visaWarnings});
  }
  if(resource==='properties'&&req.method==='POST'){
   const x=body(req);required(x,['name']);const cfg=maps.properties;const property=pick(x,cfg.allowed);property.property_code=String(property.property_code||`BLM-${crypto.randomBytes(3).toString('hex').toUpperCase()}`).trim().toUpperCase();
   if(property.total_floors==='')delete property.total_floors;const rows=await db('properties',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(property)});const settingFields=maps.settings.allowed.filter(k=>k!=='property_id');const settings={...pick(x,settingFields),property_id:rows[0].id};for(const k of ['electric_rate','water_rate','default_service_fee','billing_close_day','payment_due_day'])if(settings[k]==='')delete settings[k];await db('property_settings',{method:'POST',body:JSON.stringify(settings)});await audit('create','properties',rows[0].id,{property_code:property.property_code,name:property.name});return reply(res,201,rows[0]);
  }
  if(resource==='properties'&&req.method==='PATCH'){
   const id=String(req.query.id||'');if(!id)throw Object.assign(new Error('Thiếu ID tòa nhà'),{status:400});const x=body(req);const property=pick(x,maps.properties.allowed);if(property.property_code)property.property_code=String(property.property_code).trim().toUpperCase();
   if(property.total_floors==='')delete property.total_floors;const rows=await db(`properties?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(property)});if(!rows.length)throw Object.assign(new Error('Không tìm thấy tòa nhà'),{status:404});const settings=pick(x,maps.settings.allowed.filter(k=>k!=='property_id'));for(const k of ['electric_rate','water_rate','default_service_fee','billing_close_day','payment_due_day'])if(settings[k]==='')delete settings[k];if(Object.keys(settings).length)await db('property_settings?on_conflict=property_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({...settings,property_id:id})});await audit('update','properties',id,{...property,...settings});return reply(res,200,rows[0]);
  }
  if(req.method==='GET'&&resource==='monthly'){
   const period=String(req.query.period||new Date().toISOString().slice(0,7));const propertyId=String(req.query.property_id||'');
   const periods=propertyId?await db(`billing_periods?property_id=eq.${encodeURIComponent(propertyId)}&period=eq.${encodeURIComponent(period)}&select=id,period,status,closed_at`):[];
    const leaseCandidates=propertyId?await db('leases?property_id=eq.'+encodeURIComponent(propertyId)+'&select='+leaseSnapshotSelect+'&order=start_date.desc'):[],lease_defaults_by_room={};for(const lease of leaseCandidates)if(leaseIsCurrent(lease)&&!lease_defaults_by_room[lease.room_id])lease_defaults_by_room[lease.room_id]={lease_id:lease.id,rent:Number(lease.monthly_rent||0),service_fee:Number(lease.service_water_fee||0)};const periodId=periods[0]?.id;const rawRows=periodId?await db('monthly_room_records?select=*&billing_period_id=eq.'+encodeURIComponent(periodId)+'&order=room_id.asc'):[];const recordIds=rawRows.map(x=>x.id),invoices=recordIds.length?await db('invoices?record_id=in.('+recordIds.join(',')+')&select=record_id,paid_amount,status,locked_at'):[],invoiceByRecord=Object.fromEntries(invoices.map(x=>[x.record_id,x])),lockedRoomIds=rawRows.filter(x=>invoiceHasPayment(invoiceByRecord[x.id])).map(x=>x.room_id);const [autoDebtByRoom,autoElectricStartByRoom]=await Promise.all([previousDebtByRoom(propertyId,period),previousElectricEndByRoom(propertyId,period)]),rows=await attachRoomNumbers(rawRows,propertyId),displayRows=rows.map(x=>{const hasAutomaticDebt=Object.prototype.hasOwnProperty.call(autoDebtByRoom,x.room_id),hasAutomaticElectricStart=Object.prototype.hasOwnProperty.call(autoElectricStartByRoom,x.room_id);return {...x,previous_debt:hasAutomaticDebt?autoDebtByRoom[x.room_id]:Number(x.previous_debt||0),previous_debt_source:hasAutomaticDebt?'invoice':'manual',electric_start:hasAutomaticElectricStart?autoElectricStartByRoom[x.room_id]:Number(x.electric_start||0),electric_start_source:hasAutomaticElectricStart?'previous_month':'manual'}});return reply(res,200,{rows:displayRows,previous_debt_by_room:autoDebtByRoom,electric_start_by_room:autoElectricStartByRoom,locked_room_ids:lockedRoomIds,lease_defaults_by_room,period:periods[0]||{period,status:'open',closed_at:null}});
  }
  if(req.method==='POST'&&resource==='monthly'){
   const x=body(req);required(x,['property_id','period','room_id']);
   const propertyId=String(x.property_id),roomId=String(x.room_id),period=String(x.period);
   const room=(await db('rooms?id=eq.'+encodeURIComponent(roomId)+'&property_id=eq.'+encodeURIComponent(propertyId)+'&select=id,property_id'))[0];if(!room)throw Object.assign(new Error('Phòng không thuộc tòa nhà đã chọn'),{status:400});
   let periods=await db('billing_periods?property_id=eq.'+encodeURIComponent(propertyId)+'&period=eq.'+encodeURIComponent(period)+'&select=id,status');if(!periods.length)periods=await db('billing_periods',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({property_id:propertyId,period})});
   const periodId=periods[0].id,existingRecords=await db('monthly_room_records?billing_period_id=eq.'+encodeURIComponent(periodId)+'&room_id=eq.'+encodeURIComponent(roomId)+'&select=*'),existingRecord=existingRecords[0]||null;if(x.room_record_id&&existingRecord&&String(x.room_record_id)!==String(existingRecord.id))throw Object.assign(new Error('Bản ghi dữ liệu tháng không khớp với phòng đã chọn'),{status:400});
   const recordId=existingRecord?.id,existingInvoice=recordId?(await db('invoices?record_id=eq.'+encodeURIComponent(recordId)+'&status=neq.cancelled&select=id,paid_amount,status,locked_at'))[0]:null;if(existingInvoice&&invoiceHasPayment(existingInvoice))throw Object.assign(new Error('Phòng này đã có thanh toán, dữ liệu đã bị khóa'),{status:409});
   const defaults=(await db('property_settings?property_id=eq.'+encodeURIComponent(propertyId)+'&select=electric_rate,water_rate,default_service_fee'))[0]||{};let leaseId=null,rent=0,serviceFee=0;
   if(existingRecord){leaseId=existingRecord.lease_id||null;rent=number(existingRecord.rent??0,'Tiền thuê');serviceFee=number(existingRecord.service_fee??0,'Phí dịch vụ + nước')}else{const leaseCandidates=await db('leases?property_id=eq.'+encodeURIComponent(propertyId)+'&room_id=eq.'+encodeURIComponent(roomId)+'&select='+leaseSnapshotSelect+'&order=start_date.desc'),activeLease=leaseCandidates.find(lease=>String(lease.property_id)===propertyId&&String(lease.room_id)===roomId&&leaseIsCurrent(lease));if(activeLease){leaseId=activeLease.id;rent=number(activeLease.monthly_rent??0,'Tiền thuê');serviceFee=number(activeLease.service_water_fee??0,'Phí dịch vụ + nước')}}
   const [autoDebtByRoom,autoElectricStartByRoom]=await Promise.all([previousDebtByRoom(propertyId,period,[roomId]),previousElectricEndByRoom(propertyId,period,[roomId])]),previousDebt=Object.prototype.hasOwnProperty.call(autoDebtByRoom,roomId)?autoDebtByRoom[roomId]:number(x.previous_debt??existingRecord?.previous_debt??0,'Nợ trước'),electricStart=Object.prototype.hasOwnProperty.call(autoElectricStartByRoom,roomId)?autoElectricStartByRoom[roomId]:number(x.electric_start??existingRecord?.electric_start??0,'Điện đầu');
   const rec={property_id:propertyId,billing_period_id:periodId,room_id:roomId,lease_id:leaseId,rent,electric_start:electricStart,electric_end:number(x.electric_end??existingRecord?.electric_end??0,'Điện cuối'),electric_rate:number(existingRecord?.electric_rate??x.electric_rate??defaults.electric_rate??4000,'Giá điện'),water_start:number(existingRecord?.water_start??x.water_start??0,'Nước đầu'),water_end:number(existingRecord?.water_end??x.water_end??0,'Nước cuối'),water_rate:number(existingRecord?.water_rate??x.water_rate??defaults.water_rate??0,'Giá nước'),service_fee:serviceFee,other_fee:number(x.other_fee??existingRecord?.other_fee??0,'Phí khác'),discount:number(x.discount??existingRecord?.discount??0,'Giảm giá'),previous_debt:previousDebt,notes:x.notes!==undefined?x.notes:existingRecord?.notes??null};
   if(rec.electric_end<rec.electric_start||rec.water_end<rec.water_start)throw Object.assign(new Error('Chỉ số cuối không được nhỏ hơn chỉ số đầu'),{status:400});
   const rows=await db('monthly_room_records?on_conflict=billing_period_id,room_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(rec)});if(existingInvoice)await db('invoices?id=eq.'+encodeURIComponent(existingInvoice.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({total_amount:recordTotal(rec)})});await audit('upsert','monthly_record',rows[0].id,rec);return reply(res,200,rows[0]);
  }
  if(req.method==='POST'&&resource==='payments'){
   const x=body(req);required(x,['invoice_id','amount']);const payment={p_invoice_id:x.invoice_id,p_amount:number(x.amount,'Số tiền'),p_paid_at:x.paid_at||new Date().toISOString(),p_method:x.method||'transfer',p_reference:x.reference||null,p_notes:x.notes||null,p_idempotency_key:x.idempotency_key||null};
   const row=await db('rpc/record_payment',{method:'POST',body:JSON.stringify(payment)});await audit('create','payment',row.id,payment);return reply(res,201,row);
  }
  if(req.method==='POST'&&resource==='generate-invoices'){
   const x=body(req);required(x,['property_id','period']);
   const property=(await db(`properties?id=eq.${encodeURIComponent(x.property_id)}&select=id,property_code`))[0];if(!property)throw Object.assign(new Error('Không tìm thấy tòa nhà'),{status:404});
   let periods=await db(`billing_periods?property_id=eq.${encodeURIComponent(x.property_id)}&period=eq.${encodeURIComponent(x.period)}&select=id,status`);if(!periods.length)throw Object.assign(new Error(`Chưa có dữ liệu tháng ${String(x.period).slice(5)}/${String(x.period).slice(0,4)} để phát hành hóa đơn.`),{status:400});
    // Phát hành hóa đơn không khóa kỳ; mỗi phòng chỉ khóa sau khi đã có thanh toán.
   const rawRecords=await db(`monthly_room_records?property_id=eq.${encodeURIComponent(x.property_id)}&select=*&billing_period_id=eq.${encodeURIComponent(periods[0].id)}`);if(!rawRecords.length)throw Object.assign(new Error(`Chưa có dữ liệu tháng ${String(x.period).slice(5)}/${String(x.period).slice(0,4)} để phát hành hóa đơn.`),{status:400});const [records,autoDebtByRoom,autoElectricStartByRoom]=await Promise.all([attachRoomNumbers(rawRecords,x.property_id),previousDebtByRoom(x.property_id,x.period),previousElectricEndByRoom(x.property_id,x.period)]);
    const existingInvoices=await db(`invoices?record_id=in.(${records.map(r=>encodeURIComponent(r.id)).join(',')})&status=neq.cancelled&select=id,record_id,paid_amount,status,locked_at`),existingByRecord=Object.fromEntries(existingInvoices.map(invoice=>[invoice.record_id,invoice])),created=[];let skipped=0,updated=0;
    const recordUpdates=[],invoiceUpdates=[],newInvoices=[];
    for(const r of records){
     const existing=existingByRecord[r.id];if(existing&&invoiceHasPayment(existing)){skipped++;continue}
     const hasAutomaticDebt=Object.prototype.hasOwnProperty.call(autoDebtByRoom,r.room_id),previousDebt=hasAutomaticDebt?autoDebtByRoom[r.room_id]:Number(r.previous_debt||0),hasAutomaticElectricStart=Object.prototype.hasOwnProperty.call(autoElectricStartByRoom,r.room_id),electricStart=hasAutomaticElectricStart?autoElectricStartByRoom[r.room_id]:Number(r.electric_start||0),changes={};
     if(hasAutomaticDebt&&Number(r.previous_debt||0)!==previousDebt){changes.previous_debt=previousDebt;r.previous_debt=previousDebt}
     if(hasAutomaticElectricStart&&Number(r.electric_start||0)!==electricStart){changes.electric_start=electricStart;r.electric_start=electricStart}
     if(Object.keys(changes).length)recordUpdates.push({id:r.id,changes});
     const total=recordTotal(r),invoiceNumber=`${property.property_code}-${x.period.replace('-','')}-${r.rooms.room_number}`;
     if(existing){invoiceUpdates.push({id:existing.id,data:{issued_at:new Date().toISOString(),invoice_number:invoiceNumber,due_date:x.due_date||null,total_amount:total,status:'unpaid',locked_at:null}});updated++;continue}
     newInvoices.push({record_id:r.id,property_id:x.property_id,invoice_number:invoiceNumber,due_date:x.due_date||null,total_amount:total,status:'unpaid'});
    }
    await Promise.all(recordUpdates.map(item=>db(`monthly_room_records?id=eq.${encodeURIComponent(item.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(item.changes)})));
    const [updatedRows,createdRows]=await Promise.all([Promise.all(invoiceUpdates.map(item=>db(`invoices?id=eq.${encodeURIComponent(item.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(item.data)}))),newInvoices.length?db('invoices',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(newInvoices)}):Promise.resolve([])]);
    created.push(...updatedRows.flat(),...createdRows);
    await audit('generate','invoices',x.period,{count:created.length,skipped,updated});return reply(res,200,{count:created.length,skipped,updated,locked:false});
  }
  if(resource==='documents'&&req.method==='GET'){
   const entityType=String(req.query.entity_type||''),entityId=String(req.query.entity_id||''),propertyId=String(req.query.property_id||'');required({entity_type:entityType,entity_id:entityId},['entity_type','entity_id']);documentConfig(entityType);return reply(res,200,await getDocumentAttachments(entityType,entityId,propertyId));
  }
  if(resource==='documents'&&req.method==='POST'){
   const x=body(req),entityType=String(x.entity_type||''),entityId=String(x.entity_id||''),propertyId=String(x.property_id||'');required({entity_type:entityType,entity_id:entityId,property_id:propertyId},['entity_type','entity_id','property_id']);documentConfig(entityType);const entity=await findDocumentEntity(entityType,entityId,propertyId);if(!entity)throw Object.assign(new Error('Không tìm thấy hồ sơ hoặc hồ sơ không thuộc tòa nhà đã chọn'),{status:404});const files=Array.isArray(x.files)?x.files:[];if(!files.length)throw Object.assign(new Error('Chưa có tài liệu để tải lên'),{status:400});const uploaded=[],errors=[];for(let index=0;index<files.length;index++){const file=files[index]||{};let path='';try{const data=String(file.data||''),match=data.match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/),mime=String(file.mime_type||file.type||match?.[1]||'').toLowerCase();if(!match||!DOCUMENT_MIME_EXTENSIONS[mime]||match[1]!==mime)throw Object.assign(new Error('Chỉ hỗ trợ ảnh JPG, PNG hoặc WebP'),{status:400});const buffer=Buffer.from(match[2],'base64');if(!buffer.length||buffer.length>MAX_DOCUMENT_BYTES)throw Object.assign(new Error('Ảnh phải nhỏ hơn hoặc bằng 3 MB'),{status:413});const ext=DOCUMENT_MIME_EXTENSIONS[mime],fileName=documentFilename(file.file_name||file.name,`tai-lieu-${index+1}.${ext}`),type=documentType(entityType,file.document_type),sortOrder=Number.isFinite(Number(file.sort_order))&&Number(file.sort_order)>=0?Number(file.sort_order):index;path=`properties/${propertyId}/${entityType}/${entityId}/${crypto.randomUUID()}.${ext}`;await storageRequest(`object/${DOCUMENT_BUCKET}/${path}`,{method:'POST',headers:{'Content-Type':mime,'x-upsert':'false','cache-control':'3600'},body:buffer});const rows=await db('document_attachments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({property_id:propertyId,entity_type:entityType,entity_id:entityId,document_type:type,file_path:path,file_name:fileName,mime_type:mime,file_size:buffer.length,sort_order:sortOrder})});const attachment=rows[0];uploaded.push(attachment);await audit('upload_document',entityType,entityId,{document_id:attachment.id,file_path:path,file_name:fileName,document_type:type,size:buffer.length})}catch(error){if(path)await removeDocumentStorage(path);errors.push({file_name:documentFilename(file.file_name||file.name,`tài liệu ${index+1}`),error:error.message||'Không thể tải lên tài liệu'})}}let result=uploaded;try{result=await hydrateDocumentAttachments(uploaded)}catch(error){console.error('document signed urls',error.message)}return reply(res,uploaded.length?201:400,{attachments:result,errors,uploaded_count:uploaded.length,failed_count:errors.length});
  }
  if(resource==='documents'&&req.method==='PATCH'){
   const id=String(req.query.id||''),x=body(req);required({id},['id']);const current=(await db(`document_attachments?id=eq.${encodeURIComponent(id)}&select=*`))[0];if(!current)throw Object.assign(new Error('Không tìm thấy tài liệu'),{status:404});if(x.property_id&&String(x.property_id)!==String(current.property_id)||x.entity_type&&String(x.entity_type)!==String(current.entity_type)||x.entity_id&&String(x.entity_id)!==String(current.entity_id))throw Object.assign(new Error('Tài liệu không thuộc đúng hồ sơ đã chọn'),{status:403});const row={};if(x.document_type!==undefined)row.document_type=documentType(current.entity_type,x.document_type);if(x.sort_order!==undefined){const sortOrder=Number(x.sort_order);if(!Number.isInteger(sortOrder)||sortOrder<0)throw Object.assign(new Error('Thứ tự tài liệu không hợp lệ'),{status:400});row.sort_order=sortOrder}if(x.file_name!==undefined)row.file_name=documentFilename(x.file_name);const updated=Object.keys(row).length?await db(`document_attachments?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}):[current];await audit('update_document',current.entity_type,current.entity_id,{document_id:id,...row});return reply(res,200,(await hydrateDocumentAttachments(updated))[0]);
  }
  if(resource==='documents'&&req.method==='DELETE'){
   const id=String(req.query.id||''),propertyId=String(req.query.property_id||''),entityType=String(req.query.entity_type||''),entityId=String(req.query.entity_id||'');required({id},['id']);const current=(await db(`document_attachments?id=eq.${encodeURIComponent(id)}&select=*`))[0];if(!current)throw Object.assign(new Error('Không tìm thấy tài liệu'),{status:404});if(propertyId&&propertyId!==String(current.property_id)||entityType&&entityType!==String(current.entity_type)||entityId&&entityId!==String(current.entity_id))throw Object.assign(new Error('Tài liệu không thuộc đúng hồ sơ đã chọn'),{status:403});await db(`document_attachments?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=representation'}});const storageDeleted=await removeDocumentStorage(current.file_path);await audit('delete_document',current.entity_type,current.entity_id,{document_id:id,file_path:current.file_path,file_name:current.file_name,storage_deleted:storageDeleted});return reply(res,200,{ok:true,storage_deleted:storageDeleted});
  }
  if(req.method==='POST'&&resource==='upload'){
   const x=body(req),config={tenant:{table:'tenants',pathField:'identity_document_path',documentType:'identity'},lease:{table:'leases',pathField:'contract_document_path',documentType:'contract'}}[x.entity];if(!config)throw Object.assign(new Error('Loại tệp không hợp lệ'),{status:400});required(x,['entity_id','property_id','data']);const match=String(x.data).match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/);if(!match)throw Object.assign(new Error('Chỉ hỗ trợ ảnh JPG, PNG hoặc WebP'),{status:400});const buffer=Buffer.from(match[2],'base64');if(!buffer.length||buffer.length>MAX_DOCUMENT_BYTES)throw Object.assign(new Error('Ảnh phải nhỏ hơn hoặc bằng 3 MB'),{status:413});const target=await db(`${config.table}?id=eq.${encodeURIComponent(x.entity_id)}&property_id=eq.${encodeURIComponent(x.property_id)}&select=id`);if(!target.length)throw Object.assign(new Error('Không tìm thấy dữ liệu cần gắn ảnh'),{status:404});const ext={jpeg:'jpg',png:'png',webp:'webp'}[match[1].split('/')[1]],path=`properties/${x.property_id}/${x.entity}/${x.entity_id}/${crypto.randomUUID()}.${ext}`;await storageRequest(`object/${DOCUMENT_BUCKET}/${path}`,{method:'POST',headers:{'Content-Type':match[1],'x-upsert':'true','cache-control':'3600'},body:buffer});await db(`${config.table}?id=eq.${encodeURIComponent(x.entity_id)}&property_id=eq.${encodeURIComponent(x.property_id)}`,{method:'PATCH',body:JSON.stringify({[config.pathField]:path})});try{await db('document_attachments',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({property_id:x.property_id,entity_type:x.entity,entity_id:x.entity_id,document_type:config.documentType,file_path:path,file_name:documentFilename(x.file_name),mime_type:match[1],file_size:buffer.length,sort_order:0})})}catch(error){console.error('legacy document attachment',error.message)}const urls=await signedDocumentUrls([path]);await audit('upload_document',x.entity,x.entity_id,{file_path:path,file_name:documentFilename(x.file_name),document_type:config.documentType,size:buffer.length,legacy:true});return reply(res,201,{path,url:urls[path]||null})
  }
  if(req.method==='GET'&&resource==='reports'){const propertyId=String(req.query.property_id||''),period=String(req.query.period||''),mode=req.query.mode==='cash'?'cash':'invoice';required({property_id:propertyId,period},['property_id','period']);const [report,trend]=await Promise.all([buildReport(propertyId,period,mode),buildReportTrendSafe(propertyId,period,mode)]);report.trend=trend;return reply(res,200,report)}
  const cfg=maps[resource];if(!cfg)return reply(res,404,{error:'Chức năng không tồn tại'});
  if(req.method==='GET'&&resource==='invoices'&&req.query.period){
   const propertyId=String(req.query.property_id||''),period=String(req.query.period||'');required({property_id:propertyId,period},['property_id','period']);const data=await invoicesForPeriod(propertyId,period);return reply(res,200,sortInvoicesByRoom(await hydrateInvoiceRows(data)));
  }
  if(req.method==='GET'){const id=req.query.id?`id=eq.${encodeURIComponent(req.query.id)}&`:'';const propertyId=String(req.query.property_id||'');const direct=propertyId&&(['rooms','tenants','leases','visas','settings'].includes(resource)||resource==='invoices')?`property_id=eq.${encodeURIComponent(propertyId)}&`:'';const data=await db(`${cfg.table}?${id}${direct}select=${cfg.select||'*'}&order=${cfg.order}`);return reply(res,200,resource==='invoices'?sortInvoicesByRoom(await hydrateInvoiceRows(data)):resource==='leases'?await hydrateDocumentSummary(await hydrateLeases(data),'leases'):resource==='tenants'?await hydrateDocumentSummary(await hydrateTenants(data),'tenants'):resource==='rooms'?await hydrateRooms(data):data)}
  if(req.method==='POST'){const x=body(req);required(x,cfg.required);if(resource==='leases'&&x.status!==undefined)throw Object.assign(new Error('Trạng thái hợp đồng do hệ thống tự động xác định.'),{status:400});if(resource==='rooms'){const roomNumber=String(x.room_number||'').trim();if(!roomNumber)throw Object.assign(new Error('Vui lòng nhập số phòng.'),{status:400});x.room_number=roomNumber;const property=(await db(`properties?id=eq.${encodeURIComponent(x.property_id)}&select=id`))[0];if(!property)throw Object.assign(new Error('Không tìm thấy tòa nhà'),{status:404});await ensureUniqueRoomNumber(x.property_id,roomNumber)}const row=resource==='leases'?normalizeLeaseMoney(clean(pick(x,cfg.allowed))):clean(pick(x,cfg.allowed));let rows;try{rows=await db(cfg.table,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)})}catch(error){if(resource==='rooms'&&isRoomConflictError(error))throw Object.assign(new Error('Phòng này đã tồn tại.'),{status:409});throw error}if(resource==='leases'){await syncLeaseOccupants(rows[0].id,row.property_id,x.occupant_ids,row.representative_tenant_id);await syncRoomStatuses(row.property_id)}if(resource==='rooms')await syncRoomStatuses(row.property_id);await audit('create',resource,rows[0].id,row);return reply(res,201,rows[0])}
  if(req.method==='PATCH'){required(req.query,['id']);const x=body(req),before=resource==='leases'?(await db(`leases?id=eq.${encodeURIComponent(req.query.id)}&select=id,property_id,room_id,start_date,end_date,status`))[0]:null,isEarlyTermination=resource==='leases'&&x.status==='terminated';if(resource==='leases'){if(!before)throw Object.assign(new Error('Không tìm thấy hợp đồng'),{status:404});if(x.status!==undefined&&x.status!=='terminated')throw Object.assign(new Error('Trạng thái hợp đồng do hệ thống tự động xác định.'),{status:400});if(isEarlyTermination){const requestPropertyId=String(req.query.property_id||'');if(!requestPropertyId||requestPropertyId!==String(before.property_id))throw Object.assign(new Error('Hợp đồng không thuộc tòa nhà đã chọn'),{status:400});if(effectiveLeaseStatus(before)!=='active')throw Object.assign(new Error('Hợp đồng này hiện không còn hiệu lực.'),{status:409})}}if(resource==='rooms'){const currentRoom=(await db(`rooms?id=eq.${encodeURIComponent(req.query.id)}&select=id,property_id`))[0];if(!currentRoom)throw Object.assign(new Error('Không tìm thấy phòng'),{status:404});const requestPropertyId=String(req.query.property_id||'');if(!requestPropertyId||requestPropertyId!==String(currentRoom.property_id))throw Object.assign(new Error('Phòng không thuộc tòa nhà đã chọn'),{status:400});if(x.property_id!==undefined&&String(x.property_id)!==String(currentRoom.property_id))throw Object.assign(new Error('Không thể chuyển phòng sang tòa nhà khác bằng chức năng Sửa phòng.'),{status:400});if(x.room_number!==undefined){const roomNumber=String(x.room_number||'').trim();if(!roomNumber)throw Object.assign(new Error('Vui lòng nhập số phòng.'),{status:400});x.room_number=roomNumber;await ensureUniqueRoomNumber(currentRoom.property_id,roomNumber,req.query.id)}delete x.property_id}const row=resource==='leases'?normalizeLeaseMoney(clean(pick(x,cfg.allowed))):clean(pick(x,cfg.allowed));let rows;try{rows=await db(`${cfg.table}?id=eq.${encodeURIComponent(req.query.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)})}catch(error){if(resource==='rooms'&&isRoomConflictError(error))throw Object.assign(new Error('Phòng này đã tồn tại.'),{status:409});throw error}if(resource==='leases'){const propertyId=row.property_id||before?.property_id;if(Array.isArray(x.occupant_ids))await syncLeaseOccupants(req.query.id,propertyId,x.occupant_ids,row.representative_tenant_id??before?.representative_tenant_id);await syncRoomStatuses(propertyId)}if(resource==='rooms')await syncRoomStatuses(row.property_id||rows[0]?.property_id);await audit(isEarlyTermination?'terminate_lease_early':'update',resource,req.query.id,isEarlyTermination?{lease_id:req.query.id,room_id:before.room_id,contract_end_date:before.end_date,terminated_at:new Date().toISOString()}:row);return reply(res,200,rows[0])}
  if(req.method==='DELETE'){required(req.query,['id']);try{const before=resource==='leases'||resource==='rooms'?(await db(`${cfg.table}?id=eq.${encodeURIComponent(req.query.id)}&select=property_id`))[0]:null;const rows=await db(`${cfg.table}?id=eq.${encodeURIComponent(req.query.id)}`,{method:'DELETE',headers:{Prefer:'return=representation'}});if(!rows?.length)throw Object.assign(new Error('Không tìm thấy dữ liệu cần xóa'),{status:404});if(resource==='leases'||resource==='rooms')await syncRoomStatuses(before?.property_id||rows[0]?.property_id);await audit('delete',resource,req.query.id,{deleted:rows[0]});return reply(res,200,{ok:true})}catch(e){if(resource==='properties'&&(e.status===409||/foreign key|violates/i.test(e.message)))throw Object.assign(new Error('Không thể xóa tòa nhà đang có phòng hoặc dữ liệu liên quan'),{status:409});throw e}}
  return reply(res,405,{error:'Phương thức không hỗ trợ'});
 }catch(e){
  const status=Number.isInteger(Number(e?.status))&&Number(e.status)>=400&&Number(e.status)<=599?Number(e.status):500,upstream=Boolean(e?.retryable)||isUpstreamStatus(status)||/^UPSTREAM_/i.test(String(e?.code||'')),code=String(e?.code|| (upstream?'UPSTREAM_UNAVAILABLE':'SERVER_ERROR')),message=upstream?'Không thể tải dữ liệu.':status===500?'Lỗi máy chủ':String(e?.message||'Lỗi máy chủ');
  console.error('[API ERROR]',{requestId,resource,method:req.method,status,code,duration:Date.now()-startedAt});
  return reply(res,status,{error:message,code,retryable:upstream,requestId})
 }
};

