const crypto = require('node:crypto');

function reply(res,status,data){res.status(status).setHeader('Cache-Control','no-store').json(data)}
function safeEqual(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function role(req){const value=req.headers['x-admin-password'];if(safeEqual(value,process.env.ADMIN_PASSWORD))return'admin';if(process.env.VIEWER_PASSWORD&&safeEqual(value,process.env.VIEWER_PASSWORD))return'viewer';return null}
function body(req){return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{})}
function required(obj,fields){for(const f of fields)if(obj[f]===undefined||obj[f]===null||obj[f]==='')throw Object.assign(new Error(`Thiếu trường ${f}`),{status:400})}
function number(v,name){const n=Number(v);if(!Number.isFinite(n)||n<0)throw Object.assign(new Error(`${name} không hợp lệ`),{status:400});return n}
async function db(path,options={}){const base=(process.env.SUPABASE_URL||'').replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw Object.assign(new Error('Chưa cấu hình Supabase'),{status:503});const r=await fetch(`${base}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={message:text}}if(!r.ok)throw Object.assign(new Error(data?.message||data?.hint||'Lỗi database'),{status:r.status});return data}
const DOCUMENT_BUCKET='private-documents',MAX_DOCUMENT_BYTES=3*1024*1024;
async function storageRequest(path,options={}){const base=(process.env.SUPABASE_URL||'').replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw Object.assign(new Error('Chưa cấu hình Supabase Storage'),{status:503});const r=await fetch(`${base}/storage/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={message:text}}if(!r.ok)throw Object.assign(new Error(data?.message||data?.error||'Lỗi lưu tệp'),{status:r.status});return data}
async function signedDocumentUrls(paths){if(!paths.length)return{};const data=await storageRequest(`object/sign/${DOCUMENT_BUCKET}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paths,expiresIn:3600})});const base=(process.env.SUPABASE_URL||'').replace(/\/rest\/v1\/?$/,'').replace(/\/$/,'');return Object.fromEntries((data||[]).map(x=>[x.path,x.signedURL?.startsWith('http')?x.signedURL:`${base}/storage/v1${x.signedURL||''}`]))}
async function hydrateDocumentLinks(rows,resource){const pathField=resource==='tenants'?'identity_document_path':'contract_document_path',urlField=resource==='tenants'?'identity_document_url':'contract_document_url',paths=[...new Set(rows.map(x=>x[pathField]).filter(Boolean))];if(!paths.length)return rows.map(x=>({...x,[urlField]:null}));const urls=await signedDocumentUrls(paths);return rows.map(x=>({...x,[urlField]:x[pathField]?urls[x[pathField]]||null:null}))}
async function audit(action,type,id,details){try{await db('audit_logs',{method:'POST',body:JSON.stringify({action,entity_type:type,entity_id:String(id||''),details})})}catch(e){console.error('audit',e.message)}}
async function attachRoomNumbers(rows,propertyId=''){if(!rows.length)return rows;const filter=propertyId?`property_id=eq.${encodeURIComponent(propertyId)}&`:'';const rooms=await db(`rooms?${filter}select=id,room_number`);const byId=Object.fromEntries(rooms.map(r=>[r.id,{room_number:r.room_number}]));return rows.map(r=>({...r,rooms:byId[r.room_id]||null}))}
async function hydrateRooms(rows){if(!rows.length)return rows;const roomIds=rows.map(x=>x.id).join(','),leases=await db(`leases?room_id=in.(${roomIds})&select=room_id,monthly_rent,start_date,end_date,status&order=start_date.desc`),rentByRoom={},occupiedRoomIds=new Set();for(const lease of leases)if(effectiveLeaseStatus(lease)==='active'){occupiedRoomIds.add(lease.room_id);if(rentByRoom[lease.room_id]===undefined)rentByRoom[lease.room_id]=lease.monthly_rent}return rows.map(row=>({...row,effective_status:effectiveRoomStatus(row,occupiedRoomIds),actual_rent:rentByRoom[row.id]??null}))}
async function hydrateTenants(rows){if(!rows.length)return rows;const tenantIds=rows.map(x=>x.id).join(','),[links,representativeLeases]=await Promise.all([db(`lease_tenants?tenant_id=in.(${tenantIds})&select=tenant_id,lease_id,is_representative,move_in_date,move_out_date`),db(`leases?representative_tenant_id=in.(${tenantIds})&select=id,representative_tenant_id,start_date,end_date,status`)]);const leaseIds=[...new Set(links.map(x=>x.lease_id).filter(Boolean))].join(','),linkedLeases=leaseIds?await db(`leases?id=in.(${leaseIds})&select=id,start_date,end_date,status`):[],leaseById=Object.fromEntries([...linkedLeases,...representativeLeases].map(x=>[x.id,x])),relations={};for(const link of links){const lease=leaseById[link.lease_id];if(lease)(relations[link.tenant_id]??=[]).push({...lease,move_in_date:link.move_in_date,move_out_date:link.move_out_date})}for(const lease of representativeLeases)(relations[lease.representative_tenant_id]??=[]).push(lease);return rows.map(row=>{const items=relations[row.id]||[],lease=items.find(x=>leaseIsCurrent(x))||items.sort((a,b)=>String(b.start_date||'').localeCompare(String(a.start_date||'')))[0],leaseStatus=lease?effectiveLeaseStatus(lease):null;return {...row,rental_start_date:lease?.move_in_date||lease?.start_date||null,rental_status:leaseStatus==='active'?'active':leaseStatus==='scheduled'?'scheduled':'ended'}})}
async function syncRoomStatuses(propertyId){if(!propertyId)return;const filter=`property_id=eq.${encodeURIComponent(propertyId)}`;const [rooms,leases]=await Promise.all([db(`rooms?${filter}&select=id,status`),db(`leases?${filter}&select=room_id,status,start_date,end_date`)]);const occupied=new Set(leases.filter(leaseIsCurrent).map(x=>x.room_id));await Promise.all(rooms.filter(r=>['vacant','occupied'].includes(r.status)&&r.status!==(occupied.has(r.id)?'occupied':'vacant')).map(r=>db(`rooms?id=eq.${encodeURIComponent(r.id)}`,{method:'PATCH',body:JSON.stringify({status:occupied.has(r.id)?'occupied':'vacant'})})));}
async function previousDebtByRoom(propertyId,period,roomIds=[]){if(!propertyId||!period)return{};const property=encodeURIComponent(propertyId),previousPeriods=await db(`billing_periods?property_id=eq.${property}&period=lt.${encodeURIComponent(period)}&select=id`);const periodIds=previousPeriods.map(x=>x.id);if(!periodIds.length)return{};const roomFilter=roomIds.length?`&room_id=in.(${roomIds.join(',')})`:'';const records=await db(`monthly_room_records?property_id=eq.${property}&billing_period_id=in.(${periodIds.join(',')})${roomFilter}&select=id,room_id`);const recordIds=records.map(x=>x.id);if(!recordIds.length)return{};const invoices=await db(`invoices?record_id=in.(${recordIds.join(',')})&status=neq.cancelled&select=id,record_id,total_amount`);const invoiceIds=invoices.map(x=>x.id);const payments=invoiceIds.length?await db(`payments?invoice_id=in.(${invoiceIds.join(',')})&select=invoice_id,amount`):[];const paidByInvoice=payments.reduce((m,x)=>(m[x.invoice_id]=(m[x.invoice_id]||0)+Number(x.amount||0),m),{}),roomByRecord=Object.fromEntries(records.map(x=>[x.id,x.room_id])),debt={};for(const invoice of invoices){const remaining=Math.max(0,Number(invoice.total_amount||0)-Number(paidByInvoice[invoice.id]||0));if(remaining)debt[roomByRecord[invoice.record_id]]=(debt[roomByRecord[invoice.record_id]]||0)+remaining}return debt}
async function hydrateInvoices(rows){if(!rows.length)return rows;const recordIds=rows.map(x=>x.record_id).join(',');const records=await db(`monthly_room_records?id=in.(${recordIds})&select=*`);const roomIds=[...new Set(records.map(x=>x.room_id).filter(Boolean))].join(',');const periodIds=[...new Set(records.map(x=>x.billing_period_id).filter(Boolean))].join(',');const leaseIds=[...new Set(records.map(x=>x.lease_id).filter(Boolean))].join(',');const [rooms,periods,leases]=await Promise.all([roomIds?db(`rooms?id=in.(${roomIds})&select=id,room_number`):[],periodIds?db(`billing_periods?id=in.(${periodIds})&select=id,period`):[],leaseIds?db(`leases?id=in.(${leaseIds})&select=id,representative_tenant_id`):[]]);const tenantIds=[...new Set(leases.map(x=>x.representative_tenant_id).filter(Boolean))].join(',');const tenants=tenantIds?await db(`tenants?id=in.(${tenantIds})&select=id,full_name`):[];const roomById=Object.fromEntries(rooms.map(x=>[x.id,x])),periodById=Object.fromEntries(periods.map(x=>[x.id,x])),tenantById=Object.fromEntries(tenants.map(x=>[x.id,x])),leaseById=Object.fromEntries(leases.map(x=>[x.id,{...x,tenants:tenantById[x.representative_tenant_id]||null}])),recordById=Object.fromEntries(records.map(x=>[x.id,{...x,rooms:roomById[x.room_id]||null,billing_periods:periodById[x.billing_period_id]||null,leases:leaseById[x.lease_id]||null}]));return rows.map(x=>({...x,monthly_room_records:recordById[x.record_id]||null}))}
async function hydrateInvoicePayments(rows){if(!rows.length)return rows;const ids=rows.map(x=>x.id).join(',');const payments=await db(`payments?invoice_id=in.(${ids})&select=invoice_id,amount,method`);const totals={};for(const p of payments){const item=totals[p.invoice_id]||{transfer:0,cash:0,total:0};const amount=Number(p.amount||0);item.total+=amount;if(p.method==='transfer')item.transfer+=amount;else if(p.method==='cash')item.cash+=amount;totals[p.invoice_id]=item}return rows.map(x=>{const t=totals[x.id]||{transfer:0,cash:0,total:0};return {...x,paid_transfer:t.transfer,paid_cash:t.cash,paid_amount:t.total}})}
async function hydrateLeases(rows){if(!rows.length)return rows;const leaseIds=rows.map(x=>x.id).join(','),links=await db(`lease_tenants?lease_id=in.(${leaseIds})&select=lease_id,tenant_id,is_representative,move_in_date,move_out_date`),tenantIds=[...new Set([...links.map(x=>x.tenant_id),...rows.map(x=>x.representative_tenant_id).filter(Boolean)])].join(',');const tenants=tenantIds?await db(`tenants?id=in.(${tenantIds})&select=id,full_name,identity_number,phone,permanent_address`):[];const tenantById=Object.fromEntries(tenants.map(x=>[x.id,x]));const linksByLease={};for(const link of links){(linksByLease[link.lease_id]??=[]).push({...link,tenant:tenantById[link.tenant_id]||null})}return rows.map(row=>{const occupants=linksByLease[row.id]||[];if(row.representative_tenant_id&&!occupants.some(x=>x.tenant_id===row.representative_tenant_id))occupants.unshift({lease_id:row.id,tenant_id:row.representative_tenant_id,is_representative:true,tenant:tenantById[row.representative_tenant_id]||row.tenants||null});return {...row,effective_status:effectiveLeaseStatus(row),occupants,occupant_ids:occupants.map(x=>x.tenant_id)}})}
async function syncLeaseOccupants(leaseId,propertyId,occupantIds=[],representativeId=null){if(!leaseId||!propertyId)return;const ids=[...new Set([representativeId,...(Array.isArray(occupantIds)?occupantIds:[])].filter(Boolean))];await db(`lease_tenants?lease_id=eq.${encodeURIComponent(leaseId)}`,{method:'DELETE'});if(ids.length)await db('lease_tenants',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(ids.map(tenantId=>({lease_id:leaseId,property_id:propertyId,tenant_id:tenantId,is_representative:tenantId===representativeId})))});}
function reportBounds(period){const [year,month]=String(period).split('-').map(Number);if(!year||!month||month<1||month>12)throw Object.assign(new Error('Kỳ báo cáo không hợp lệ'),{status:400});const start=new Date(`${String(year).padStart(4,'0')}-${String(month).padStart(2,'0')}-01T00:00:00+07:00`),nextMonth=month===12?1:month+1,nextYear=month===12?year+1:year,end=new Date(`${String(nextYear).padStart(4,'0')}-${String(nextMonth).padStart(2,'0')}-01T00:00:00+07:00`);return{start:start.toISOString(),end:end.toISOString()}}
function reportStatus(paid,total){if(paid<=0)return'unpaid';if(paid<total)return'partial';return'paid'}
function reportMethod(method){return method==='transfer'?'Chuyển khoản':method==='cash'?'Tiền mặt':method==='other'?'Khác':method||'—'}
function listFilter(field,values){const items=[...new Set(values.map(x=>String(x??'').trim()).filter(Boolean))];if(!items.length)return'';if(items.length===1)return`${field}=eq.${encodeURIComponent(items[0])}`;return`${field}=in.(${items.map(x=>encodeURIComponent(x)).join(',')})`}
async function buildReport(propertyId,period,mode='invoice'){
 const propertyIdEncoded=encodeURIComponent(propertyId),property=(await db(`properties?id=eq.${propertyIdEncoded}&select=id,name,property_code`))[0];
 if(!property)throw Object.assign(new Error('Không tìm thấy tòa nhà'),{status:404});
 const [rooms,leases]=await Promise.all([
  db(`rooms?property_id=eq.${propertyIdEncoded}&select=id,room_number,status`),
  db(`leases?property_id=eq.${propertyIdEncoded}&select=id,room_id,representative_tenant_id,start_date,end_date,status`)
 ]);
 const occupiedRoomIds=new Set(leases.filter(leaseIsCurrent).map(x=>x.room_id));
 let invoices=[],records=[],selectedPayments=[];
 if(mode==='cash'){
  const bounds=reportBounds(period);
  selectedPayments=await db(`payments?paid_at=gte.${encodeURIComponent(bounds.start)}&paid_at=lt.${encodeURIComponent(bounds.end)}&select=id,invoice_id,amount,paid_at,method&order=paid_at.desc`);
  const selectedInvoiceIds=[...new Set(selectedPayments.map(x=>x.invoice_id).filter(Boolean))];
  invoices=selectedInvoiceIds.length?await db(`invoices?property_id=eq.${propertyIdEncoded}&${listFilter('id',selectedInvoiceIds)}&status=neq.cancelled&select=id,record_id,total_amount,status`):[];
  const recordIds=invoices.map(x=>x.record_id).filter(Boolean);
  records=recordIds.length?await db(`monthly_room_records?property_id=eq.${propertyIdEncoded}&${listFilter('id',recordIds)}&select=*`):[];
 }else{
  const periods=await db(`billing_periods?property_id=eq.${propertyIdEncoded}&period=eq.${encodeURIComponent(period)}&select=id,period`),periodId=periods[0]?.id;
  if(periodId){
   records=await db(`monthly_room_records?property_id=eq.${propertyIdEncoded}&billing_period_id=eq.${encodeURIComponent(periodId)}&select=*`);
   const recordIds=records.map(x=>x.id);
   invoices=recordIds.length?await db(`invoices?property_id=eq.${propertyIdEncoded}&${listFilter('record_id',recordIds)}&status=neq.cancelled&select=id,record_id,total_amount,status`):[];
  }
 }
 const invoiceIds=invoices.map(x=>x.id),recordById=Object.fromEntries(records.map(x=>[x.id,x])),allPayments=invoiceIds.length?await db(`payments?${listFilter('invoice_id',invoiceIds)}&select=id,invoice_id,amount,paid_at,method&order=paid_at.desc`):[],paymentsByInvoice={};
 for(const payment of allPayments)(paymentsByInvoice[payment.invoice_id]??=[]).push(payment);
 const selectedByInvoice={};for(const payment of selectedPayments)(selectedByInvoice[payment.invoice_id]??=[]).push(payment);
 const recordPeriodIds=[...new Set(records.map(x=>x.billing_period_id).filter(Boolean))],periods=recordPeriodIds.length?await db(`billing_periods?property_id=eq.${propertyIdEncoded}&${listFilter('id',recordPeriodIds)}&select=id,period`):[],periodById=Object.fromEntries(periods.map(x=>[x.id,x.period]));
 // Báo cáo chỉ lấy người đại diện của hợp đồng đang có hiệu lực hiện tại.
 // Không dùng lease_id lịch sử trong monthly_room_records để xác định khách thuê.
 const activeLeaseByRoom={};
 for(const lease of leases){
  if(!leaseIsCurrent(lease)||activeLeaseByRoom[lease.room_id])continue;
  activeLeaseByRoom[lease.room_id]=lease;
 }
 const reportRoomIds=new Set(records.map(x=>x.room_id).filter(Boolean));
 const tenantIds=[...new Set(Object.values(activeLeaseByRoom).filter(x=>reportRoomIds.has(x.room_id)).map(x=>x.representative_tenant_id).filter(Boolean))];
 const tenants=tenantIds.length?await db(`tenants?property_id=eq.${propertyIdEncoded}&${listFilter('id',tenantIds)}&select=id,full_name`):[];
 const tenantById=Object.fromEntries(tenants.map(x=>[x.id,x])),roomById=Object.fromEntries(rooms.map(x=>[x.id,x]));
 const rows=invoices.map(invoice=>{
  const record=recordById[invoice.record_id];if(!record)return null;
  const all=paymentsByInvoice[invoice.id]||[],relevant=mode==='cash'?(selectedByInvoice[invoice.id]||[]):all,total=Number(invoice.total_amount||0),paidAll=all.reduce((sum,x)=>sum+Number(x.amount||0),0),paid=relevant.reduce((sum,x)=>sum+Number(x.amount||0),0),room=roomById[record.room_id],activeLease=activeLeaseByRoom[record.room_id],tenant=tenantById[activeLease?.representative_tenant_id],electric=Math.max(0,Number(record.electric_end||0)-Number(record.electric_start||0))*Number(record.electric_rate||0),water=Math.max(0,Number(record.water_end||0)-Number(record.water_start||0))*Number(record.water_rate||0),latest=relevant.slice().sort((a,b)=>String(b.paid_at||'').localeCompare(String(a.paid_at||'')))[0],methods=[...new Set(relevant.map(x=>reportMethod(x.method)))];
  return{invoice_id:invoice.id,property_name:property.name,property_code:property.property_code,room_id:record.room_id,room_number:room?.room_number||'—',tenant_name:tenant?.full_name||'—',period:periodById[record.billing_period_id]||period,rent_amount:Number(record.rent||0),electricity_amount:electric,water_amount:water,service_amount:Number(record.service_fee||0),other_amount:Number(record.other_fee||0),previous_debt:Number(record.previous_debt||0),discount_amount:Number(record.discount||0),total_amount:total,paid_amount:paid,paid_total:paidAll,debt_amount:Math.max(0,total-paidAll),payment_status:reportStatus(paidAll,total),latest_payment_at:latest?.paid_at||null,payment_method:methods.join(', ')||'—'};
 }).filter(Boolean);
 const totals=rows.reduce((sum,row)=>{for(const key of ['rent_amount','electricity_amount','water_amount','service_amount','other_amount','previous_debt','discount_amount','total_amount','paid_amount','debt_amount'])sum[key]=(sum[key]||0)+Number(row[key]||0);return sum},{});
 return{property,period,mode,rooms:{total:rooms.length,occupied:rooms.filter(x=>effectiveRoomStatus(x,occupiedRoomIds)==='occupied').length,vacant:rooms.filter(x=>effectiveRoomStatus(x,occupiedRoomIds)==='vacant').length},totals,rows}
}
function reportRecentPeriods(period,count=6){const [year,month]=String(period).split('-').map(Number),result=[];for(let i=count-1;i>=0;i--){const date=new Date(year,month-1-i,1),y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0');result.push(`${y}-${m}`)}return result}
async function buildReportTrendSafe(propertyId,period,mode){const periods=reportRecentPeriods(period,6),encoded=encodeURIComponent(propertyId);if(mode==='cash'){const first=reportBounds(periods[0]),last=reportBounds(periods[periods.length-1]),propertyInvoices=await db(`invoices?property_id=eq.${encoded}&status=neq.cancelled&select=id`),invoiceIds=propertyInvoices.map(x=>x.id),payments=invoiceIds.length?await db(`payments?${listFilter('invoice_id',invoiceIds)}&paid_at=gte.${encodeURIComponent(first.start)}&paid_at=lt.${encodeURIComponent(last.end)}&select=amount,paid_at`):[],byPeriod=Object.fromEntries(periods.map(x=>[x,0]));for(const payment of payments){const date=new Date(payment.paid_at),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit'}).formatToParts(date),key=`${parts.find(x=>x.type==='year').value}-${parts.find(x=>x.type==='month').value}`;if(key in byPeriod)byPeriod[key]+=Number(payment.amount||0)}return periods.map(x=>({period:x,total:0,paid:byPeriod[x]||0}))}const periodRows=await db(`billing_periods?property_id=eq.${encoded}&${listFilter('period',periods)}&select=id,period`),periodById=Object.fromEntries(periodRows.map(x=>[x.id,x.period])),periodIds=periodRows.map(x=>x.id),records=periodIds.length?await db(`monthly_room_records?property_id=eq.${encoded}&${listFilter('billing_period_id',periodIds)}&select=id,billing_period_id`):[],recordById=Object.fromEntries(records.map(x=>[x.id,x.billing_period_id])),recordIds=records.map(x=>x.id),invoices=recordIds.length?await db(`invoices?property_id=eq.${encoded}&${listFilter('record_id',recordIds)}&status=neq.cancelled&select=id,record_id,total_amount`):[],invoiceIds=invoices.map(x=>x.id),payments=invoiceIds.length?await db(`payments?${listFilter('invoice_id',invoiceIds)}&select=invoice_id,amount`):[],paidByInvoice={};for(const payment of payments)paidByInvoice[payment.invoice_id]=(paidByInvoice[payment.invoice_id]||0)+Number(payment.amount||0);const totals=Object.fromEntries(periods.map(x=>[x,{total:0,paid:0}]));for(const invoice of invoices){const key=periodById[recordById[invoice.record_id]];if(key){totals[key].total+=Number(invoice.total_amount||0);totals[key].paid+=paidByInvoice[invoice.id]||0}}return periods.map(x=>({period:x,total:totals[x].total,paid:totals[x].paid}))}
const maps={
 properties:{table:'properties',select:'*,property_settings(*),rooms(count)',order:'name.asc',required:['name'],allowed:['property_code','name','short_name','address','phone','owner_name','owner_phone','email','tax_code','total_floors','notes']},
 settings:{table:'property_settings',order:'created_at.asc',required:['property_id'],allowed:['property_id','electric_rate','water_rate','default_service_fee','billing_close_day','payment_due_day','bank_name','bank_bin','bank_account','bank_account_name','qr_template','invoice_note']},
 rooms:{table:'rooms',order:'room_number.asc',required:['property_id','room_number'],allowed:['property_id','room_number','floor','area','base_rent','status','notes']},
 tenants:{table:'tenants',order:'full_name.asc',required:['property_id','full_name'],allowed:['property_id','full_name','phone','email','nationality','identity_type','identity_number','date_of_birth','permanent_address','emergency_contact','notes']},
 leases:{table:'leases',select:'*,rooms!leases_room_id_fkey(room_number),tenants!leases_representative_tenant_id_fkey(full_name,phone)',order:'end_date.asc',required:['property_id','room_id','start_date','end_date'],allowed:['property_id','room_id','representative_tenant_id','start_date','end_date','monthly_rent','deposit_amount','payment_due_day','status','ended_at','end_reason','deposit_refunded','notes']},
 visas:{table:'tenant_visas',select:'*,tenants!tenant_visas_tenant_id_fkey(full_name,nationality,phone)',order:'expiry_date.asc',required:['property_id','tenant_id','expiry_date'],allowed:['property_id','tenant_id','visa_number','visa_type','issued_date','expiry_date','issuing_country','document_url','status','notes']},
 invoices:{table:'invoices',select:'*',order:'issued_at.desc',required:['record_id'],allowed:['record_id','property_id','invoice_number','issued_at','due_date','total_amount','paid_amount','status','locked_at','cancelled_at','cancel_reason']}
};
function pick(input,fields){return Object.fromEntries(fields.filter(k=>input[k]!==undefined).map(k=>[k,input[k]]))}
function clean(row){const nullable=new Set(['representative_tenant_id','lease_id','date_of_birth','ended_at','issued_date','due_date']);const numeric=new Set(['floor','area','base_rent','total_floors','monthly_rent','deposit_amount','payment_due_day','deposit_refunded','electric_rate','water_rate','default_service_fee','billing_close_day']);for(const k of Object.keys(row))if(row[k]===''){if(nullable.has(k))row[k]=null;else if(numeric.has(k))delete row[k]}return row}
function days(date){return Math.ceil((new Date(`${date}T00:00:00`)-new Date(new Date().toISOString().slice(0,10)+'T00:00:00'))/86400000)}
function warning(d){return d<0?'expired':d<=7?'danger':d<=30?'urgent':d<=60?'warning':'safe'}
function todayVN(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}).format(new Date())}
function effectiveLeaseStatus(lease){if(lease.status==='terminated')return'terminated';if(lease.status==='draft')return'draft';const today=todayVN();if(lease.start_date&&String(lease.start_date).slice(0,10)>today)return'scheduled';if(lease.end_date&&String(lease.end_date).slice(0,10)<today)return'expired';return'active'}
function leaseIsCurrent(lease){return effectiveLeaseStatus(lease)==='active'}
function effectiveRoomStatus(room,occupiedRoomIds){if(['maintenance','reserved'].includes(room.status))return room.status;return occupiedRoomIds.has(room.id)?'occupied':'vacant'}
function invoiceHasPayment(invoice){return Number(invoice?.paid_amount||0)>0||['partial','paid'].includes(invoice?.status)}
function recordTotal(record){const electric=(Number(record.electric_end||0)-Number(record.electric_start||0))*Number(record.electric_rate||0),water=(Number(record.water_end||0)-Number(record.water_start||0))*Number(record.water_rate||0);return Math.max(0,Number(record.rent||0)+electric+water+Number(record.service_fee||0)+Number(record.other_fee||0)+Number(record.previous_debt||0)-Number(record.discount||0))}

module.exports=async function handler(req,res){
 const userRole=role(req);if(!userRole)return reply(res,401,{error:'Mật khẩu không đúng'});
 try{
  const resource=String(req.query.resource||'dashboard');
  if(req.method!=='GET'&&userRole!=='admin')return reply(res,403,{error:'Tài khoản chỉ có quyền xem'});
  if(req.method==='GET'&&resource==='session')return reply(res,200,{role:userRole});
  if(req.method==='GET'&&resource==='dashboard'){
    const propertyId=String(req.query.property_id||''),from=String(req.query.from_period||''),to=String(req.query.to_period||'');if(from&&to&&from>to)throw Object.assign(new Error('Tháng bắt đầu không được lớn hơn tháng kết thúc'),{status:400});const filter=propertyId?`property_id=eq.${encodeURIComponent(propertyId)}&`:'';const periodFilter=(from?`&period=gte.${encodeURIComponent(from)}`:'')+(to?`&period=lte.${encodeURIComponent(to)}`:'');
     const [rooms,leases,visas,periods]=await Promise.all([db(`rooms?${filter}select=id,status`),db(`leases?${filter}select=id,room_id,start_date,end_date,status`),db(`tenant_visas?${filter}status=eq.active&select=id,expiry_date`),propertyId?db(`billing_periods?property_id=eq.${encodeURIComponent(propertyId)}${periodFilter}&select=id,period`):[]]);const periodIds=periods.map(x=>x.id);const records=periodIds.length?await db(`monthly_room_records?property_id=eq.${encodeURIComponent(propertyId)}&billing_period_id=in.(${periodIds.join(',')})&select=id`):[];const recordIds=records.map(x=>x.id);const invoices=recordIds.length?await db(`invoices?record_id=in.(${recordIds.join(',')})&status=neq.cancelled&select=id,total_amount`):[];const invoiceIds=invoices.map(x=>x.id);const payments=invoiceIds.length?await db(`payments?invoice_id=in.(${invoiceIds.join(',')})&select=invoice_id,amount`):[];const paidByInvoice=payments.reduce((m,x)=>(m[x.invoice_id]=(m[x.invoice_id]||0)+Number(x.amount||0),m),{}),paid=payments.reduce((s,x)=>s+Number(x.amount||0),0),debt=invoices.reduce((s,x)=>s+Math.max(0,Number(x.total_amount||0)-Number(paidByInvoice[x.id]||0)),0),currentLeases=leases.filter(leaseIsCurrent),occupiedRoomIds=new Set(currentLeases.map(x=>x.room_id));
     return reply(res,200,{period:{from:from||null,to:to||null},rooms:{total:rooms.length,occupied:rooms.filter(x=>effectiveRoomStatus(x,occupiedRoomIds)==='occupied').length,vacant:rooms.filter(x=>effectiveRoomStatus(x,occupiedRoomIds)==='vacant').length},paid,debt,leaseWarnings:currentLeases.map(x=>({...x,days:days(x.end_date),level:warning(days(x.end_date))})).filter(x=>x.days<=60),visaWarnings:visas.map(x=>({...x,days:days(x.expiry_date),level:warning(days(x.expiry_date))})).filter(x=>x.days<=60)});
  }
  if(resource==='properties'&&req.method==='POST'){
   const x=body(req);required(x,['name']);const cfg=maps.properties;const property=pick(x,cfg.allowed);property.property_code=String(property.property_code||`BLM-${crypto.randomBytes(3).toString('hex').toUpperCase()}`).trim().toUpperCase();
   if(property.total_floors==='')delete property.total_floors;const rows=await db('properties',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(property)});const settingFields=maps.settings.allowed.filter(k=>k!=='property_id');const settings={...pick(x,settingFields),property_id:rows[0].id};for(const k of ['electric_rate','water_rate','default_service_fee','billing_close_day','payment_due_day'])if(settings[k]==='')delete settings[k];await db('property_settings',{method:'POST',body:JSON.stringify(settings)});await audit('create','properties',rows[0].id,{property_code:property.property_code,name:property.name});return reply(res,201,rows[0]);
  }
  if(resource==='properties'&&req.method==='PATCH'){
   const id=String(req.query.id||'');if(!id)throw Object.assign(new Error('Thiếu ID tòa nhà'),{status:400});const x=body(req);const property=pick(x,maps.properties.allowed);if(property.property_code)property.property_code=String(property.property_code).trim().toUpperCase();
   if(property.total_floors==='')delete property.total_floors;const rows=await db(`properties?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(property)});if(!rows.length)throw Object.assign(new Error('Không tìm thấy tòa nhà'),{status:404});const settings=pick(x,maps.settings.allowed.filter(k=>k!=='property_id'));for(const k of ['electric_rate','water_rate','default_service_fee','billing_close_day','payment_due_day'])if(settings[k]==='')delete settings[k];if(Object.keys(settings).length)await db('property_settings?on_conflict=property_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({...settings,property_id:id})});await audit('update','properties',id,{...property,...settings});return reply(res,200,rows[0]);
  }
  if(req.method==='GET'&&resource==='monthly'){
   const period=String(req.query.period||new Date().toISOString().slice(0,7));const propertyId=String(req.query.property_id||'');
   const periods=propertyId?await db(`billing_periods?property_id=eq.${encodeURIComponent(propertyId)}&period=eq.${encodeURIComponent(period)}&select=id,period,status,closed_at`):[];
    const periodId=periods[0]?.id;const rawRows=periodId?await db(`monthly_room_records?select=*&billing_period_id=eq.${encodeURIComponent(periodId)}&order=room_id.asc`):[];const recordIds=rawRows.map(x=>x.id),invoices=recordIds.length?await db(`invoices?record_id=in.(${recordIds.join(',')})&select=record_id,paid_amount,status,locked_at`):[],invoiceByRecord=Object.fromEntries(invoices.map(x=>[x.record_id,x])),lockedRoomIds=rawRows.filter(x=>invoiceHasPayment(invoiceByRecord[x.id])).map(x=>x.room_id);const debtByRoom=await previousDebtByRoom(propertyId,period);const rows=await attachRoomNumbers(rawRows,propertyId);return reply(res,200,{rows:rows.map(x=>({...x,previous_debt:debtByRoom[x.room_id]||0})),previous_debt_by_room:debtByRoom,locked_room_ids:lockedRoomIds,period:periods[0]||{period,status:'open',closed_at:null}});
  }
  if(req.method==='POST'&&resource==='monthly'){
   const x=body(req);required(x,['property_id','period','room_id']);
   let periods=await db(`billing_periods?property_id=eq.${encodeURIComponent(x.property_id)}&period=eq.${encodeURIComponent(x.period)}&select=id,status`);if(!periods.length)periods=await db('billing_periods',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({property_id:x.property_id,period:x.period})});
    const existingRecords=await db(`monthly_room_records?billing_period_id=eq.${encodeURIComponent(periods[0].id)}&room_id=eq.${encodeURIComponent(x.room_id)}&select=id`),recordId=x.room_record_id||existingRecords[0]?.id,existingInvoice=recordId?(await db(`invoices?record_id=eq.${encodeURIComponent(recordId)}&status=neq.cancelled&select=id,paid_amount,status,locked_at`))[0]:null;if(existingInvoice&&invoiceHasPayment(existingInvoice))throw Object.assign(new Error('Phòng này đã có thanh toán, dữ liệu đã bị khóa'),{status:409});
   const defaults=(await db(`property_settings?property_id=eq.${x.property_id}&select=electric_rate,water_rate,default_service_fee`))[0]||{};
    const leaseCandidates=x.lease_id?[]:await db(`leases?property_id=eq.${encodeURIComponent(x.property_id)}&room_id=eq.${encodeURIComponent(x.room_id)}&select=id,start_date,end_date,status&order=start_date.desc`),activeLease=leaseCandidates.find(leaseIsCurrent);const leaseId=x.lease_id||activeLease?.id||null;const previousDebt=(await previousDebtByRoom(x.property_id,x.period,[x.room_id]))[x.room_id]||0;
   const rec={property_id:x.property_id,billing_period_id:periods[0].id,room_id:x.room_id,lease_id:leaseId,rent:number(x.rent||0,'Tiền thuê'),electric_start:number(x.electric_start||0,'Điện đầu'),electric_end:number(x.electric_end||0,'Điện cuối'),electric_rate:number(x.electric_rate??defaults.electric_rate??4000,'Giá điện'),water_start:number(x.water_start||0,'Nước đầu'),water_end:number(x.water_end||0,'Nước cuối'),water_rate:number(x.water_rate??defaults.water_rate??0,'Giá nước'),service_fee:number(x.service_fee??defaults.default_service_fee??0,'Dịch vụ'),other_fee:number(x.other_fee||0,'Phí khác'),discount:number(x.discount||0,'Giảm giá'),previous_debt:previousDebt,notes:x.notes||null};
   if(rec.electric_end<rec.electric_start||rec.water_end<rec.water_start)throw Object.assign(new Error('Chỉ số cuối không được nhỏ hơn chỉ số đầu'),{status:400});
    const rows=await db('monthly_room_records?on_conflict=billing_period_id,room_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(rec)});if(existingInvoice){await db(`invoices?id=eq.${encodeURIComponent(existingInvoice.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({total_amount:recordTotal(rec),status:'unpaid',locked_at:null})})}await audit('upsert','monthly_record',rows[0].id,rec);return reply(res,200,rows[0]);
  }
  if(req.method==='POST'&&resource==='payments'){
   const x=body(req);required(x,['invoice_id','amount']);const payment={p_invoice_id:x.invoice_id,p_amount:number(x.amount,'Số tiền'),p_paid_at:x.paid_at||new Date().toISOString(),p_method:x.method||'transfer',p_reference:x.reference||null,p_notes:x.notes||null,p_idempotency_key:x.idempotency_key||null};
   const row=await db('rpc/record_payment',{method:'POST',body:JSON.stringify(payment)});await audit('create','payment',row.id,payment);return reply(res,201,row);
  }
  if(req.method==='POST'&&resource==='generate-invoices'){
   const x=body(req);required(x,['property_id','period']);
   const property=(await db(`properties?id=eq.${encodeURIComponent(x.property_id)}&select=id,property_code`))[0];if(!property)throw Object.assign(new Error('Không tìm thấy tòa nhà'),{status:404});
   let periods=await db(`billing_periods?property_id=eq.${encodeURIComponent(x.property_id)}&period=eq.${encodeURIComponent(x.period)}&select=id,status`);if(!periods.length)periods=await db('billing_periods',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({property_id:x.property_id,period:x.period})});
    // Phát hành hóa đơn không khóa kỳ; mỗi phòng chỉ khóa sau khi đã có thanh toán.
   const rawRecords=await db(`monthly_room_records?property_id=eq.${encodeURIComponent(x.property_id)}&select=*&billing_period_id=eq.${encodeURIComponent(periods[0].id)}`);const records=await attachRoomNumbers(rawRecords,x.property_id);
    const created=[];let skipped=0,updated=0;
    for(const r of records){const existing=(await db(`invoices?record_id=eq.${encodeURIComponent(r.id)}&status=neq.cancelled&select=id,paid_amount,status,locked_at`))[0],total=recordTotal(r),invoiceNumber=`${property.property_code}-${x.period.replace('-','')}-${r.rooms.room_number}`;if(existing){if(invoiceHasPayment(existing)){skipped++;continue}const rows=await db(`invoices?id=eq.${encodeURIComponent(existing.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({issued_at:new Date().toISOString(),invoice_number:invoiceNumber,due_date:x.due_date||null,total_amount:total,status:'unpaid',locked_at:null})});created.push(rows[0]);updated++;continue}const inv={record_id:r.id,property_id:x.property_id,invoice_number:invoiceNumber,due_date:x.due_date||null,total_amount:total,status:'unpaid'};const rows=await db('invoices',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(inv)});created.push(rows[0])}
    await audit('generate','invoices',x.period,{count:created.length,skipped,updated});return reply(res,200,{count:created.length,skipped,updated,locked:false});
  }
  if(req.method==='POST'&&resource==='upload'){
   const x=body(req),config={tenant:{table:'tenants',pathField:'identity_document_path'},lease:{table:'leases',pathField:'contract_document_path'}}[x.entity];if(!config)throw Object.assign(new Error('Loại tệp không hợp lệ'),{status:400});required(x,['entity_id','property_id','data']);const match=String(x.data).match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/);if(!match)throw Object.assign(new Error('Chỉ hỗ trợ ảnh JPG, PNG hoặc WebP'),{status:400});const buffer=Buffer.from(match[2],'base64');if(!buffer.length||buffer.length>MAX_DOCUMENT_BYTES)throw Object.assign(new Error('Ảnh phải nhỏ hơn hoặc bằng 3 MB'),{status:413});const target=await db(`${config.table}?id=eq.${encodeURIComponent(x.entity_id)}&property_id=eq.${encodeURIComponent(x.property_id)}&select=id`);if(!target.length)throw Object.assign(new Error('Không tìm thấy dữ liệu cần gắn ảnh'),{status:404});const ext={jpeg:'jpg',png:'png',webp:'webp'}[match[1].split('/')[1]],path=`properties/${x.property_id}/${x.entity}/${x.entity_id}/${crypto.randomUUID()}.${ext}`;await storageRequest(`object/${DOCUMENT_BUCKET}/${path}`,{method:'POST',headers:{'Content-Type':match[1],'x-upsert':'true','cache-control':'3600'},body:buffer});await db(`${config.table}?id=eq.${encodeURIComponent(x.entity_id)}&property_id=eq.${encodeURIComponent(x.property_id)}`,{method:'PATCH',body:JSON.stringify({[config.pathField]:path})});const urls=await signedDocumentUrls([path]);await audit('upload',x.entity,x.entity_id,{path,content_type:match[1],size:buffer.length});return reply(res,201,{path,url:urls[path]||null})
  }
  if(req.method==='GET'&&resource==='reports'){const propertyId=String(req.query.property_id||''),period=String(req.query.period||''),mode=req.query.mode==='cash'?'cash':'invoice';required({property_id:propertyId,period},['property_id','period']);const report=await buildReport(propertyId,period,mode);report.trend=await buildReportTrendSafe(propertyId,period,mode);return reply(res,200,report)}
  const cfg=maps[resource];if(!cfg)return reply(res,404,{error:'Chức năng không tồn tại'});
  if(req.method==='GET'){const id=req.query.id?`id=eq.${encodeURIComponent(req.query.id)}&`:'';const propertyId=String(req.query.property_id||'');const direct=propertyId&&(['rooms','tenants','leases','visas','settings'].includes(resource)||resource==='invoices')?`property_id=eq.${encodeURIComponent(propertyId)}&`:'';const data=await db(`${cfg.table}?${id}${direct}select=${cfg.select||'*'}&order=${cfg.order}`);return reply(res,200,resource==='invoices'?await hydrateInvoices(await hydrateInvoicePayments(data)):resource==='leases'?await hydrateDocumentLinks(await hydrateLeases(data),'leases'):resource==='tenants'?await hydrateDocumentLinks(await hydrateTenants(data),'tenants'):resource==='rooms'?await hydrateRooms(data):data)}
  if(req.method==='POST'){const x=body(req);required(x,cfg.required);const row=clean(pick(x,cfg.allowed));const rows=await db(cfg.table,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});if(resource==='leases'){await syncLeaseOccupants(rows[0].id,row.property_id,x.occupant_ids,row.representative_tenant_id);await syncRoomStatuses(row.property_id)}if(resource==='rooms')await syncRoomStatuses(row.property_id);await audit('create',resource,rows[0].id,row);return reply(res,201,rows[0])}
  if(req.method==='PATCH'){required(req.query,['id']);const x=body(req),before=resource==='leases'?(await db(`leases?id=eq.${encodeURIComponent(req.query.id)}&select=property_id,representative_tenant_id`))[0]:null;const row=clean(pick(x,cfg.allowed));const rows=await db(`${cfg.table}?id=eq.${encodeURIComponent(req.query.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});if(resource==='leases'){const propertyId=row.property_id||before?.property_id;if(Array.isArray(x.occupant_ids))await syncLeaseOccupants(req.query.id,propertyId,x.occupant_ids,row.representative_tenant_id??before?.representative_tenant_id);await syncRoomStatuses(propertyId)}if(resource==='rooms')await syncRoomStatuses(row.property_id||rows[0]?.property_id);await audit('update',resource,req.query.id,row);return reply(res,200,rows[0])}
  if(req.method==='DELETE'){required(req.query,['id']);try{const before=resource==='leases'||resource==='rooms'?(await db(`${cfg.table}?id=eq.${encodeURIComponent(req.query.id)}&select=property_id`))[0]:null;const rows=await db(`${cfg.table}?id=eq.${encodeURIComponent(req.query.id)}`,{method:'DELETE',headers:{Prefer:'return=representation'}});if(!rows?.length)throw Object.assign(new Error('Không tìm thấy dữ liệu cần xóa'),{status:404});if(resource==='leases'||resource==='rooms')await syncRoomStatuses(before?.property_id||rows[0]?.property_id);await audit('delete',resource,req.query.id,{deleted:rows[0]});return reply(res,200,{ok:true})}catch(e){if(resource==='properties'&&(e.status===409||/foreign key|violates/i.test(e.message)))throw Object.assign(new Error('Không thể xóa tòa nhà đang có phòng hoặc dữ liệu liên quan'),{status:409});throw e}}
  return reply(res,405,{error:'Phương thức không hỗ trợ'});
 }catch(e){console.error(e);return reply(res,e.status||500,{error:e.status?e.message:'Lỗi máy chủ'})}
};

